import '../../models/lesson.dart';
import '../../models/question.dart';

/// 數學課程（國小 1–2 年級，上下學期）
///
/// **108 課綱數學領域**：低年級著重數與量、幾何、關係、度量與實測、資料與統計之經驗；
/// 以下單元主題與學期分段對應《十二年國教課程綱要》，不依特定版本教科書。
const List<Lesson> kMathLessons = [
  // ======== 一年級 上學期 ========
  Lesson(
    id: 'cl-m-1-1-u1',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 1,
    title: '10 以內的數',
    summary: '認識 0–10 並數數',
    content: '我們從 0 數到 10：\n0、1、2、3、4、5、6、7、8、9、10\n\n看圖數數：\n🍎🍎🍎 → 3 顆蘋果\n⭐⭐⭐⭐⭐ → 5 顆星星\n\n把相同數量的東西和數字連起來！',
    estimatedMinutes: 10,
    objectives: [
      '能唱數並指認 0–10',
      '能將數量與數字對應',
    ],
    keyPoints: [
      '數字順序有前後關係',
      '點數時一個物件對一個數',
    ],
    vocabulary: [
      VocabItem(term: '數量', meaning: '東西有幾個', example: '3 顆蘋果'),
      VocabItem(term: '唱數', meaning: '依序念出數字', example: '0、1、2…'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '🐶🐶🐶🐶 有幾隻小狗？',
        options: ['3', '4', '5', '6'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '數字 7 的前一個數是？',
        options: ['5', '6', '8', '9'],
        correctIndex: 1,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '從 1 數到 5，中間不會出現的是？',
        options: ['2', '3', '4', '6'],
        correctIndex: 3,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-1-u2',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 2,
    title: '比多少',
    summary: '比較數量與大小',
    content: '用「一對一」的方式比一比：\n🍎🍎🍎🍎\n🍐🍐🍐\n\n蘋果比較「多」，梨子比較「少」。\n\n4 比 3 大　寫作 4 > 3\n3 比 4 小　寫作 3 < 4',
    estimatedMinutes: 10,
    objectives: [
      '能用一對一對應比多少',
      '能使用 > 與 < 表示大小',
    ],
    keyPoints: [
      '先對齊再比較，較容易看出多寡',
      '數字大表示數量比較多（同單位下）',
    ],
    vocabulary: [
      VocabItem(term: '多', meaning: '數量比較大', example: '蘋果比較多'),
      VocabItem(term: '少', meaning: '數量比較小', example: '梨子比較少'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '5 和 8 哪個比較大？',
        options: ['5', '8', '一樣大', '不知道'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '小明 6 支鉛筆，小華 4 支鉛筆，誰的比較多？',
        options: ['小明', '小華', '一樣多', '都沒有'],
        correctIndex: 0,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-1-u3',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 3,
    title: '合起來和拿走',
    summary: '加法與減法的意義',
    content: '【合起來】\n🍬🍬 和 🍬🍬🍬 合起來 = 🍬🍬🍬🍬🍬\n2 + 3 = 5\n\n【拿走】\n🍪🍪🍪🍪🍪 拿走 2 個 = 🍪🍪🍪\n5 - 2 = 3',
    estimatedMinutes: 10,
    objectives: [
      '能說出「合起來」與「拿走」的意義',
      '能解 10 以內加減問題',
    ],
    keyPoints: [
      '加法是把兩堆合起來',
      '減法是從整體拿走一部分',
    ],
    vocabulary: [
      VocabItem(term: '合起來', meaning: '兩部分變成全部', example: '2+3=5'),
      VocabItem(term: '拿走', meaning: '從全部去掉一部分', example: '5-2=3'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '4 + 3 = ?',
        options: ['5', '6', '7', '8'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '9 - 4 = ?',
        options: ['3', '4', '5', '6'],
        correctIndex: 2,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '姊姊有 6 顆糖，給妹妹 2 顆，還剩幾顆？',
        options: ['2', '3', '4', '5'],
        correctIndex: 2,
        explanation: '6 − 2 = 4 顆',
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-1-u4',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 4,
    title: '順序與位置',
    summary: '認識第幾個',
    content: '小朋友排隊：\n小明、小華、小美、小強、小芳\n\n從前面數：\n第 1 個是小明，第 3 個是小美。\n\n從後面數：\n第 1 個是小芳，第 2 個是小強。',
    estimatedMinutes: 10,
    objectives: [
      '能辨識「第幾個」與「從哪一邊數」',
      '能解簡單排隊序位問題',
    ],
    keyPoints: [
      '「第幾個」要說清楚從哪一端開始數',
      '總人數與從後往前數可以互相推算',
    ],
    vocabulary: [
      VocabItem(term: '第幾個', meaning: '順序中的位置', example: '從前面數第 3 個'),
      VocabItem(term: '前面／後面', meaning: '數的方向', example: '從後面數'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '🐰🐱🐶🐼，從左邊數，🐶 是第幾個？',
        options: ['第 1', '第 2', '第 3', '第 4'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '5 位小朋友排一列，小強從後面數是第 2 個，那他從前面數是第幾個？',
        options: ['第 2', '第 3', '第 4', '第 5'],
        correctIndex: 2,
        explanation: '5 − 2 + 1 = 4，從前面數是第 4 個。',
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-1-u5',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 5,
    title: '比長短',
    summary: '認識長度比較',
    content: '把兩個東西的一端對齊，再看另一端，就能比出長短。\n\n鉛筆 ▬▬▬▬▬\n尺子 ▬▬▬▬▬▬▬\n\n尺子比較「長」，鉛筆比較「短」。',
    estimatedMinutes: 10,
    objectives: [
      '能說出比長短要先一端對齊',
      '能用長、短描述比較結果',
    ],
    keyPoints: [
      '沒對齊容易比錯',
      '眼睛看與實際量要配合',
    ],
    vocabulary: [
      VocabItem(term: '長', meaning: '一端到另一端的距離較遠', example: '尺較長'),
      VocabItem(term: '短', meaning: '距離較近', example: '鉛筆較短'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '比較兩個東西的長短時，要先做什麼？',
        options: ['閉上眼睛', '兩端都不對齊', '一端對齊', '放進抽屜'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-1-u6',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 6,
    title: '幾點鐘',
    summary: '認識整點時間',
    content: '時鐘上有「短針」和「長針」。\n長針指向 12，短針指向哪裡就是幾點鐘。\n\n例如：短針指 3，長針指 12 → 3 點\n短針指 7，長針指 12 → 7 點',
    estimatedMinutes: 10,
    objectives: [
      '能讀出整點時間（長針指 12）',
      '能將生活事件與整點連結',
    ],
    keyPoints: [
      '短針指幾、長針指 12 就是幾點',
      '先認識整點再學半點、幾分',
    ],
    vocabulary: [
      VocabItem(term: '時針', meaning: '較短的指針', example: '指 8 是 8 點多'),
      VocabItem(term: '分針', meaning: '較長的指針', example: '指 12 是整點'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '短針指 5，長針指 12，現在是幾點？',
        options: ['5 點', '12 點', '5:30', '12:05'],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '上學時，時鐘的短針指 8，長針指 12，現在是？',
        options: ['8 點半', '8 點', '12 點', '不知道'],
        correctIndex: 1,
      ),
    ],
  ),

  // ======== 一年級 下學期 ========
  Lesson(
    id: 'cl-m-1-2-u1',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 1,
    title: '20 以內的數',
    summary: '10 到 20 的認識',
    content: '10 個一數就是「一個十」。\n\n10 + 3 = 13（一個十和三個一）\n10 + 7 = 17（一個十和七個一）\n\n從 10 數到 20：\n10、11、12、13、14、15、16、17、18、19、20',
    estimatedMinutes: 10,
    objectives: [
      '能說出 11–20 的組成（幾個十與幾個一）',
      '能依序數出 10 到 20',
    ],
    keyPoints: [
      '10 個一是 1 個十',
      '十位與個位要分開看',
    ],
    vocabulary: [
      VocabItem(term: '一個十', meaning: '10 個一合起來', example: '10+3=13'),
      VocabItem(term: '個位', meaning: '右邊第一位', example: '13 的 3'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '16 是由幾個十和幾個一組成？',
        options: ['1 個十 6 個一', '6 個十 1 個一', '16 個十', '16 個一'],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '18 的後一個數是？',
        options: ['17', '19', '20', '28'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-2-u2',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 2,
    title: '加減直式計算',
    summary: '20 以內的加減',
    content: '直式計算時，個位對個位，十位對十位。\n\n  1 2\n+   5\n────\n  1 7\n\n  1 8\n-   6\n────\n  1 2',
    estimatedMinutes: 10,
    objectives: [
      '能將個位與十位對齊做直式加減',
      '能解 20 以內加減文字題',
    ],
    keyPoints: [
      '直式要位值對齊',
      '先算個位再算十位',
    ],
    vocabulary: [
      VocabItem(term: '直式', meaning: '上下對齊的算式寫法', example: '個位對個位'),
      VocabItem(term: '借位', meaning: '個位不夠減時向十位借', example: '12-7'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '13 + 5 = ?',
        options: ['17', '18', '19', '20'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '20 − 8 = ?',
        options: ['10', '11', '12', '13'],
        correctIndex: 2,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '小明有 15 張貼紙，送給弟弟 7 張，還剩幾張？',
        options: ['6', '7', '8', '9'],
        correctIndex: 2,
        explanation: '15 − 7 = 8 張',
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-2-u3',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 3,
    title: '100 以內的數',
    summary: '兩位數的認識',
    content: '幾十幾：\n• 35 = 3 個十 + 5 個一\n• 72 = 7 個十 + 2 個一\n\n十位數字變大 → 整個數字也變大\n\n比較大小：48 < 53（先比十位，4 < 5）',
    estimatedMinutes: 10,
    objectives: [
      '能說出兩位數的十位與個位意義',
      '能比較 100 以內數的大小',
    ],
    keyPoints: [
      '先比十位，十位相同再比個位',
      '位值不同，數字代表的數就不同',
    ],
    vocabulary: [
      VocabItem(term: '十位', meaning: '表示幾個十', example: '67 的 6'),
      VocabItem(term: '位值', meaning: '數字所在位置代表的數值', example: '35 的 3 是 30'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '67 的十位是？',
        options: ['6', '7', '60', '67'],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '哪一個數最大？',
        options: ['45', '54', '49', '52'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-2-u4',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 4,
    title: '幾月幾日',
    summary: '認識月曆',
    content: '一年有 12 個月。\n\n每個月的天數不一樣：\n• 1、3、5、7、8、10、12 月有 31 天\n• 4、6、9、11 月有 30 天\n• 2 月平年 28 天，閏年 29 天\n\n一週有 7 天：星期一到星期日',
    estimatedMinutes: 10,
    objectives: [
      '能說出一年有 12 個月、一週有 7 天',
      '能辨識月曆上的日期與星期',
    ],
    keyPoints: [
      '大月、小月天數不同',
      '2 月在平年、閏年差一天',
    ],
    vocabulary: [
      VocabItem(term: '月曆', meaning: '記錄日期的工具', example: '找今天是幾月幾日'),
      VocabItem(term: '星期', meaning: '一週的七天名稱', example: '星期一到日'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '一個星期有幾天？',
        options: ['5 天', '6 天', '7 天', '10 天'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '一年有幾個月？',
        options: ['10', '11', '12', '13'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-1-2-u5',
    subjectId: 'math',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 5,
    title: '認識錢幣',
    summary: '1、5、10 元與付錢找錢',
    content: '我們用「元」來買東西。\n\n常見硬幣與紙鈔：\n• 1 元、5 元、10 元硬幣\n• 50 元、100 元紙鈔\n\n買 7 元的飲料，付 10 元，找回 10 − 7 = 3 元。\n付錢時要數清楚，也要愛惜錢幣。',
    estimatedMinutes: 10,
    objectives: [
      '能辨認 1、5、10 元等常見錢幣',
      '能解決 20 元以內簡單付錢、找錢',
    ],
    keyPoints: [
      '不同面值可以合起來剛好等於價錢',
      '找錢用「付的 − 價錢」',
    ],
    vocabulary: [
      VocabItem(term: '元', meaning: '錢的單位', example: '10 元'),
      VocabItem(term: '找錢', meaning: '多付的部分退回', example: '付 10 元買 7 元找 3 元'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '下面哪一個硬幣面值最小？',
        options: ['10 元', '5 元', '1 元', '50 元'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '一枝筆 8 元，付 10 元，應找回多少？',
        options: ['1 元', '2 元', '3 元', '8 元'],
        correctIndex: 1,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '5 元和 5 元合起來是幾元？',
        options: ['5 元', '10 元', '55 元', '25 元'],
        correctIndex: 1,
      ),
    ],
  ),


  // ======== 二年級 上學期 ========
  Lesson(
    id: 'cl-m-2-1-u1',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 1,
    title: '200 以內的數',
    summary: '認識百位數',
    content: '10 個十就是 1 個百。\n\n100、101、102、…、199、200\n\n位值：\n百位｜十位｜個位\n  1  ｜ 2 ｜ 5   →  125',
    estimatedMinutes: 10,
    objectives: [
      '能說出三位數的百、十、個位意義',
      '能在 200 以內讀寫與比較數',
    ],
    keyPoints: [
      '10 個十是 1 個百',
      '百位數變大，整個數通常變大',
    ],
    vocabulary: [
      VocabItem(term: '百位', meaning: '表示幾個百', example: '138 的 1'),
      VocabItem(term: '位值表', meaning: '百十個排列', example: '125'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '138 的百位數字是？',
        options: ['1', '3', '8', '138'],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '100 裡面有幾個十？',
        options: ['1', '10', '100', '1000'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-1-u2',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 2,
    title: '加減直式（進位與借位）',
    summary: '兩位數的加減',
    content: '【進位加法】\n  2 7\n+ 1 6\n────\n  4 3\n個位 7+6=13，寫 3 進 1；十位 2+1+1=4。\n\n【借位減法】\n  5 2\n- 1 8\n────\n  3 4\n個位 2 不夠減 8，向十位借 1 變 12−8=4；十位 4−1=3。',
    estimatedMinutes: 10,
    objectives: [
      '能處理兩位數進位加與借位減',
      '能解生活中找錢、剩多少的問題',
    ],
    keyPoints: [
      '個位滿十要進位到十位',
      '個位不夠減要向十位借一當十',
    ],
    vocabulary: [
      VocabItem(term: '進位', meaning: '個位相加滿十往前进 1', example: '7+6=13 寫 3 進 1'),
      VocabItem(term: '借位', meaning: '從十位借 1 當 10 個一', example: '12-8'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '46 + 37 = ?',
        options: ['73', '83', '93', '103'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '71 − 29 = ?',
        options: ['40', '41', '42', '52'],
        correctIndex: 2,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '媽媽買了 68 元的水果，付 100 元，找回多少錢？',
        options: ['22 元', '32 元', '42 元', '52 元'],
        correctIndex: 1,
        explanation: '100 − 68 = 32 元',
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-1-u3',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 3,
    title: '長度（公分）',
    summary: '認識公分尺',
    content: '1 公分可以寫作 1 cm。\n\n用尺量長度時：\n① 一端對齊 0\n② 另一端讀刻度\n\n一枝鉛筆 ≈ 14 cm\n一支手機 ≈ 15 cm',
    estimatedMinutes: 10,
    objectives: [
      '能用公分尺量長度並讀刻度',
      '能選擇合適的長度單位描述物品',
    ],
    keyPoints: [
      '量長度起點對齊 0',
      '估測與實測可以互相檢查',
    ],
    vocabulary: [
      VocabItem(term: '公分', meaning: '常用長度單位', example: '寫成 cm'),
      VocabItem(term: '刻度', meaning: '尺上的細小標記', example: '讀幾公分'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '量長度時，起點要對齊哪一個刻度？',
        options: ['1', '0', '5', '10'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪個物品大約是 15 公分？',
        options: ['一張桌子', '一隻手機', '一台冰箱', '一根頭髮'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-1-u4',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 4,
    title: '四邊形與三角形',
    summary: '認識平面圖形',
    content: '• 三角形：3 個邊、3 個角\n• 四邊形：4 個邊、4 個角\n  – 正方形：4 邊都一樣長\n  – 長方形：對邊一樣長\n\n數一數：\n🔺 有 3 個邊\n⬛ 有 4 個邊',
    estimatedMinutes: 10,
    objectives: [
      '能辨識三角形與四邊形',
      '能說出正方形、長方形的邊長特色',
    ],
    keyPoints: [
      '三角形有三邊三角',
      '四邊形有四邊四角',
    ],
    vocabulary: [
      VocabItem(term: '正方形', meaning: '四邊等長且有四個直角', example: '方格本'),
      VocabItem(term: '長方形', meaning: '對邊等長、四個直角', example: '門片'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '正方形有幾個邊？',
        options: ['3', '4', '5', '6'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一個不是四邊形？',
        options: ['正方形', '長方形', '三角形', '平行四邊形'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-1-u5',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 5,
    title: '乘法的意義',
    summary: '幾個幾相加',
    content: '「幾個幾」就是乘法：\n\n3 個 4 相加：4 + 4 + 4 = 12\n寫作：4 × 3 = 12\n\n2 個 5 相加：5 + 5 = 10\n寫作：5 × 2 = 10',
    estimatedMinutes: 10,
    objectives: [
      '能將「幾個幾」寫成乘法算式',
      '能解簡單乘法情境題',
    ],
    keyPoints: [
      '乘法是相同加數的簡寫',
      '4×3 與 3×4 的意義不同但結果可相同（交換律）',
    ],
    vocabulary: [
      VocabItem(term: '幾個幾', meaning: '相同數加幾次', example: '3 個 4'),
      VocabItem(term: '乘號', meaning: '× 表示乘法', example: '4×3'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「3 個 6」可以寫成？',
        options: ['3 + 6', '6 + 3', '6 × 3', '3 − 6'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '5 × 4 等於？',
        options: ['9', '20', '25', '40'],
        correctIndex: 1,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '一盒 2 個雞蛋，3 盒共有幾個？',
        options: ['5', '6', '7', '8'],
        correctIndex: 1,
        explanation: '2 × 3 = 6 個',
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-1-u6',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 6,
    title: '分類與資料',
    summary: '做記號、數數、簡單表格',
    content: '把東西「分類」後，用「畫正」或「打勾」記錄每一類有幾個，就是資料整理的第一步。\n\n例：班上同學最喜歡的水果，分蘋果、香蕉、葡萄三類，一個一個問，記錄人數。\n\n最後可以比一比哪一類最多、哪一類最少。',
    estimatedMinutes: 10,
    objectives: [
      '能依指定標準做分類',
      '能用畫記或表格呈現各類的數量',
    ],
    keyPoints: [
      '分類標準要清楚，大家才數得一樣',
      '數完要檢查總數有沒有漏掉',
    ],
    vocabulary: [
      VocabItem(term: '分類', meaning: '依相同性質歸在一起', example: '依顏色分'),
      VocabItem(term: '資料', meaning: '收集到的數量訊息', example: '最喜歡的水果人數'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「把鉛筆和尺分開放」是在做什麼？',
        options: ['亂丟', '分類', '吃東西', '睡覺'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '記錄「喜歡蘋果的人數」時，下面哪一個方法合理？',
        options: ['不問就亂寫', '一個一個問，用畫正或數字記錄', '只問一個人代表全班', '用猜的'],
        correctIndex: 1,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '分類後，想知道「哪一類最多」，要？',
        options: ['不數', '比較每一類的數量', '只選自己喜歡的', '隨便畫圖'],
        correctIndex: 1,
      ),
    ],
  ),


  // ======== 二年級 下學期 ========
  Lesson(
    id: 'cl-m-2-2-u1',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 1,
    title: '1000 以內的數',
    summary: '認識千位',
    content: '10 個百就是 1 個千。\n\n例：三位數 527，百位｜十位｜個位\n  5 ｜ 2 ｜ 7   →  527，讀作「五百二十七」。\n1000 讀作「一千」，是 10 個百合起來。',
    estimatedMinutes: 10,
    objectives: [
      '能讀寫 1000 以內的數並說出位名',
      '能比較數的大小與接近程度',
    ],
    keyPoints: [
      '千位、百位、十位、個位由左而右',
      '接近 1000 的數，百位與十位都較大',
    ],
    vocabulary: [
      VocabItem(term: '一千', meaning: '10 個百', example: '1000'),
      VocabItem(term: '最接近', meaning: '和目標差最小的數', example: '998 接近 1000'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '567 讀作？',
        options: ['五百六十七', '五十六七', '五六七', '五千六百七十'],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一個數最接近 1000？',
        options: ['500', '899', '998', '1100'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-2-u2',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 2,
    title: '九九乘法（2、5、10）',
    summary: '基礎乘法表',
    content: '【2 的乘法】\n2 × 1=2、×2=4、×3=6、×4=8、×5=10、×6=12、×7=14、×8=16、×9=18\n\n【5 的乘法】\n5 × 1=5、×2=10、×3=15、…、×9=45\n\n【10 的乘法】\n10 × 1=10、×2=20、…、×9=90',
    estimatedMinutes: 10,
    objectives: [
      '能熟練 2、5、10 的乘法',
      '能解價錢與數量的乘法問題',
    ],
    keyPoints: [
      '用圖像或跳數幫助記憶',
      '乘法與加法可以互相驗證',
    ],
    vocabulary: [
      VocabItem(term: '九九乘法', meaning: '兩數相乘的結果表', example: '5×6=30'),
      VocabItem(term: '倍', meaning: '幾個相同數', example: '2 的 5 倍'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '5 × 6 = ?',
        options: ['25', '30', '35', '40'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '2 × 8 = ?',
        options: ['10', '12', '14', '16'],
        correctIndex: 3,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '一支棒棒糖 10 元，買 3 支要多少錢？',
        options: ['20 元', '30 元', '40 元', '50 元'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-2-u3',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 3,
    title: '毫米（mm）',
    summary: '更小的長度單位',
    content: '比公分更小的單位是毫米 (mm)。\n\n1 公分 = 10 毫米\n3 cm = 30 mm\n5 cm = 50 mm\n\n公分尺上，小格子就是 1 毫米。',
    estimatedMinutes: 10,
    objectives: [
      '能說出 1 公分等於 10 毫米',
      '能進行公分與毫米換算',
    ],
    keyPoints: [
      '毫米用在更精細的長度',
      '小格數量 ×1 就是 mm',
    ],
    vocabulary: [
      VocabItem(term: '毫米', meaning: '比公分小的單位', example: '寫成 mm'),
      VocabItem(term: '換算', meaning: '不同單位間的等量關係', example: '4cm=40mm'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '4 公分等於幾毫米？',
        options: ['4', '14', '40', '400'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '20 mm 等於幾公分？',
        options: ['0.2 cm', '2 cm', '20 cm', '200 cm'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-2-u4',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 4,
    title: '容量與重量',
    summary: '初步認識升、公斤',
    content: '【容量】裝多少水的多少\n• 牛奶盒 ≈ 1 公升 (L)\n• 水壺 ≈ 500 毫升 (mL)\n\n【重量】物品有多重\n• 小朋友書包 ≈ 3 公斤 (kg)\n• 一顆蘋果 ≈ 200 公克 (g)',
    estimatedMinutes: 10,
    objectives: [
      '能區分容量與重量常用單位',
      '能依生活經驗估測大約量',
    ],
    keyPoints: [
      '量液體用公升、毫升',
      '量物體輕重用公克、公斤',
    ],
    vocabulary: [
      VocabItem(term: '公升', meaning: '容量單位', example: '牛奶盒約 1L'),
      VocabItem(term: '公斤', meaning: '重量單位', example: '書包約 3kg'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '量水壺裡有多少水，應該使用什麼單位？',
        options: ['公分', '公升', '公斤', '小時'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪個物品大約 1 公斤？',
        options: ['一粒米', '一本書', '一袋白米 (1 kg)', '一棟房子'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-2-u5',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 5,
    title: '分數的初步',
    summary: '幾分之一',
    content: '把一個東西平分成幾份，其中的一份就是「幾分之一」。\n\n🍕 分成 2 份 → 每一份是 1/2\n🍰 分成 4 份 → 每一份是 1/4\n\n讀作：二分之一、四分之一',
    estimatedMinutes: 10,
    objectives: [
      '能說出平分後「一份」是幾分之一',
      '能讀出常見分數詞',
    ],
    keyPoints: [
      '要「平分」每一份才一樣大',
      '分母表示分成幾份、分子表示取幾份',
    ],
    vocabulary: [
      VocabItem(term: '二分之一', meaning: '平分兩份取一份', example: '1/2'),
      VocabItem(term: '四分之一', meaning: '平分四份取一份', example: '1/4'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '一塊披薩平分成 4 份，1 份是？',
        options: ['1/2', '1/3', '1/4', '1/5'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「1/2」讀作？',
        options: ['一二', '一除以二', '二分之一', '一分之二'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-m-2-2-u6',
    subjectId: 'math',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 6,
    title: '時間（幾時幾分）',
    summary: '讀出幾點幾分',
    content: '時鐘長針走一圈 = 60 分鐘 = 1 小時。\n長針每走 1 格 = 5 分鐘。\n\n例：\n• 短針在 3 和 4 之間、長針指 6 → 3:30\n• 短針在 7 和 8 之間、長針指 3 → 7:15',
    estimatedMinutes: 10,
    objectives: [
      '能讀出幾點幾分',
      '能說出 1 小時等於 60 分鐘',
    ],
    keyPoints: [
      '長針每走一大格是 5 分鐘',
      '短針在兩數之間要讀較小的時',
    ],
    vocabulary: [
      VocabItem(term: '幾分', meaning: '長針位置', example: '指 6 是 30 分'),
      VocabItem(term: '一刻', meaning: '15 分鐘', example: '7:15'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '長針指 6，代表幾分？',
        options: ['6 分', '15 分', '30 分', '60 分'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '一小時等於幾分鐘？',
        options: ['10', '30', '60', '100'],
        correctIndex: 2,
      ),
    ],
  ),
];
