import '../../models/question.dart';

/// 延伸題庫 – 按學科×年級分類，對照 108 課綱 1–2 年級內容設計。
/// 用於「複習」和「每日複習」功能，
/// 讓學生能練到比該課課文更多的題目。
///
/// Key 格式：'<subjectId>-<grade>'，例如 'math-1'、'chinese-2'
String _key(String subjectId, int grade) => '$subjectId-$grade';

const Map<String, List<Question>> kReviewPool = {
  // ============ 數學 一年級 ============
  'math-1': [
    Question(
      id: 'rp-m1-01',
      type: QuestionType.multipleChoice,
      prompt: '3 + 4 = ?',
      options: ['6', '7', '8', '9'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-02',
      type: QuestionType.multipleChoice,
      prompt: '小明有 5 顆糖果，再拿 3 顆，總共有幾顆？',
      options: ['6 顆', '7 顆', '8 顆', '9 顆'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-03',
      type: QuestionType.multipleChoice,
      prompt: '10 - 4 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-04',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個數字最大？',
      options: ['7', '9', '5', '3'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-05',
      type: QuestionType.multipleChoice,
      prompt: '6 + 3 = ?',
      options: ['8', '9', '10', '11'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-06',
      type: QuestionType.multipleChoice,
      prompt: '8 - 3 = ?',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-07',
      type: QuestionType.multipleChoice,
      prompt: '10 裡面有幾個 5？',
      options: ['1 個', '2 個', '3 個', '4 個'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-08',
      type: QuestionType.multipleChoice,
      prompt: '2 + 2 + 2 = ?',
      options: ['4', '5', '6', '7'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-09',
      type: QuestionType.multipleChoice,
      prompt: '比 7 多 3 的數是?',
      options: ['9', '10', '11', '12'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-10',
      type: QuestionType.multipleChoice,
      prompt: '15 和 18 中間，哪個數字比較大？',
      options: ['15', '18', '一樣大', '不確定'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-11',
      type: QuestionType.multipleChoice,
      prompt: '9 - 9 = ?',
      options: ['0', '1', '9', '18'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-m1-12',
      type: QuestionType.multipleChoice,
      prompt: '三角形有幾個角？',
      options: ['2 個', '3 個', '4 個', '5 個'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-13',
      type: QuestionType.multipleChoice,
      prompt: '正方形有幾個邊？',
      options: ['3 個', '4 個', '5 個', '6 個'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-14',
      type: QuestionType.multipleChoice,
      prompt: '今天星期三，明天是星期幾？',
      options: ['星期二', '星期四', '星期五', '星期日'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-15',
      type: QuestionType.multipleChoice,
      prompt: '一小時有幾分鐘？',
      options: ['30 分鐘', '50 分鐘', '60 分鐘', '100 分鐘'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-16',
      type: QuestionType.multipleChoice,
      prompt: '5 + ? = 10',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-17',
      type: QuestionType.multipleChoice,
      prompt: '12 - ? = 7',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-18',
      type: QuestionType.multipleChoice,
      prompt: '數一數：1、2、3、4、？，下一個是?',
      options: ['5', '6', '7', '8'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-m1-19',
      type: QuestionType.multipleChoice,
      prompt: '10、20、30、？',
      options: ['35', '40', '45', '50'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-20',
      type: QuestionType.multipleChoice,
      prompt: '一枝鉛筆比一支尺長還是短？',
      options: ['一樣長', '筆比較短', '筆比較長', '無法比較'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-21',
      type: QuestionType.multipleChoice,
      prompt: '1 + 9 = ?',
      options: ['8', '9', '10', '11'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-22',
      type: QuestionType.multipleChoice,
      prompt: '7 比 4 多幾？',
      options: ['1', '2', '3', '4'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-23',
      type: QuestionType.multipleChoice,
      prompt: '8 以內，比 5 大的數有幾個？（只算 6、7、8 這幾個）',
      options: ['2 個', '3 個', '4 個', '5 個'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-24',
      type: QuestionType.multipleChoice,
      prompt: '⬛⬛⬛⬛⬛⬛ 圖中黑色方塊有幾個？',
      options: ['4', '5', '6', '7'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-25',
      type: QuestionType.multipleChoice,
      prompt: '「第 1、第 2、第 3 個」是在說什麼？',
      options: ['多寡', '順序', '形狀', '顏色'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-26',
      type: QuestionType.multipleChoice,
      prompt: '0 + 5 = ?',
      options: ['0', '5', '6', '10'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-27',
      type: QuestionType.multipleChoice,
      prompt: '圓形有幾條邊是「直線的」？',
      options: ['0 條', '1 條', '2 條', '3 條'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-m1-28',
      type: QuestionType.multipleChoice,
      prompt: '5 以內的數，哪一個是「2 的鄰居」和「4 的鄰居」？',
      options: ['1', '2', '3', '4'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-29',
      type: QuestionType.multipleChoice,
      prompt: '3 + 2 + 1 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-30',
      type: QuestionType.multipleChoice,
      prompt: '媽媽有 4 顆雞蛋，用掉 0 顆，還剩幾顆？',
      options: ['0', '3', '4', '5'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-31',
      type: QuestionType.multipleChoice,
      prompt: '下面哪一個數和 4 一樣大？',
      options: ['2 + 1', '1 + 3', '1 + 2', '0 + 2'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-32',
      type: QuestionType.multipleChoice,
      prompt: '兩邊一樣多的時候，我們可以說什麼？',
      options: ['比較多', '一樣多', '沒有', '不知道'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-33',
      type: QuestionType.multipleChoice,
      prompt: '5、6、7、8、9，5 的下一個是？',
      options: ['4', '5', '6', '10'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-34',
      type: QuestionType.multipleChoice,
      prompt: '把 3 和 2 合起來，我們用哪個式子？',
      options: ['3 - 2', '3 + 2', '3 = 2', '2 = 2'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-35',
      type: QuestionType.multipleChoice,
      prompt: '11 的個位是幾？',
      options: ['0', '1', '2', '10'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-36',
      type: QuestionType.multipleChoice,
      prompt: '7 在數線上比 6 往哪一邊比較遠？',
      options: ['一樣', '往大的方向遠一點', '往小', '不確定'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-37',
      type: QuestionType.multipleChoice,
      prompt: '10 的一半可以想成 5 和 5 合起來。半個小時是幾分？',
      options: ['20 分', '25 分', '30 分', '40 分'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-38',
      type: QuestionType.multipleChoice,
      prompt: '教室裡第一排、第二排，是在分什麼？',
      options: ['顏色', '順序和位置', '氣溫', '人數的總和'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-39',
      type: QuestionType.multipleChoice,
      prompt: '1、3、5、7、9 中，3 的下一個數是？',
      options: ['1', '4', '5', '6'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-40',
      type: QuestionType.multipleChoice,
      prompt: '2 + 2 = 4，若另一題寫 2 + 2 = 2，你覺得？',
      options: [
        '一樣對',
        '可能算錯了，要重算或檢查',
        '不用理',
        '2 比較大',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-41',
      type: QuestionType.multipleChoice,
      prompt: '「長」和「短」是什麼的詞？',
      options: ['數字大小', '長度', '時間的星期', '重量'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-42',
      type: QuestionType.multipleChoice,
      prompt: '3 和 1 兩邊的數字要湊到 4，我們可以寫成？',
      options: ['3 - 1 = 4', '3 + 1 = 4', '3 = 1', '4 - 1 = 3'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-43',
      type: QuestionType.multipleChoice,
      prompt: '三角形是幾條邊圍成的封閉圖形？',
      options: ['2 條', '3 條', '4 條', '5 條'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-44',
      type: QuestionType.multipleChoice,
      prompt: '4 + 0 和 0 + 4，答案是？',
      options: ['0', '2', '4', '8'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-45',
      type: QuestionType.multipleChoice,
      prompt: '一個圖案照規律 2、4、6、8，下一个是？',
      options: ['7', '9', '10', '12'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-46',
      type: QuestionType.multipleChoice,
      prompt: '貼紙一包 6 元，付 10 元，應找回幾元？',
      options: ['3 元', '4 元', '5 元', '16 元'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m1-47',
      type: QuestionType.multipleChoice,
      prompt: '1 元硬幣和 5 元硬幣合起來是幾元？',
      options: ['4 元', '5 元', '6 元', '15 元'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m1-48',
      type: QuestionType.multipleChoice,
      prompt: '下面哪一種說法比較愛惜錢幣？',
      options: [
        '亂丟、用腳踢硬幣',
        '收進錢包、交給大人保管或存起來',
        '把硬幣當玩具丟著玩',
        '把紙鈔撕破',
      ],
      correctIndex: 1,
    ),
  ],

  // ============ 數學 二年級 ============
  'math-2': [
    Question(
      id: 'rp-m2-01',
      type: QuestionType.multipleChoice,
      prompt: '25 + 14 = ?',
      options: ['38', '39', '40', '41'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-02',
      type: QuestionType.multipleChoice,
      prompt: '48 - 23 = ?',
      options: ['15', '25', '35', '45'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-03',
      type: QuestionType.multipleChoice,
      prompt: '3 × 4 = ?',
      options: ['7', '12', '15', '16'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-04',
      type: QuestionType.multipleChoice,
      prompt: '2 的 5 倍是?',
      options: ['7', '10', '12', '20'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-05',
      type: QuestionType.multipleChoice,
      prompt: '5 × 6 = ?',
      options: ['25', '30', '35', '40'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-06',
      type: QuestionType.multipleChoice,
      prompt: '100 - 35 = ?',
      options: ['55', '65', '75', '85'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-07',
      type: QuestionType.multipleChoice,
      prompt: '有 6 個盤子，每盤 3 顆水餃，共幾顆水餃？',
      options: ['9 顆', '12 顆', '15 顆', '18 顆'],
      correctIndex: 3,
    ),
    Question(
      id: 'rp-m2-08',
      type: QuestionType.multipleChoice,
      prompt: '4 × 4 = ?',
      options: ['8', '12', '16', '20'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-09',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個是偶數？',
      options: ['7', '9', '12', '13'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-10',
      type: QuestionType.multipleChoice,
      prompt: '一元硬幣 5 個是多少錢？',
      options: ['1 元', '5 元', '10 元', '50 元'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-11',
      type: QuestionType.multipleChoice,
      prompt: '72 比 27 大多少？',
      options: ['35', '45', '55', '65'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-12',
      type: QuestionType.multipleChoice,
      prompt: '9 × 2 = ?',
      options: ['11', '16', '18', '20'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-13',
      type: QuestionType.multipleChoice,
      prompt: '現在 2 點 30 分，再過半小時是幾點？',
      options: ['3:00', '3:30', '2:45', '4:00'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-m2-14',
      type: QuestionType.multipleChoice,
      prompt: '一個長方形有幾個直角？',
      options: ['2 個', '3 個', '4 個', '6 個'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-15',
      type: QuestionType.multipleChoice,
      prompt: '8 × 3 = ?',
      options: ['18', '21', '24', '27'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-16',
      type: QuestionType.multipleChoice,
      prompt: '7 + 7 + 7 + 7 = ?',
      options: ['21', '24', '28', '32'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-17',
      type: QuestionType.multipleChoice,
      prompt: '36 ÷ 6 可以用哪個乘法求出?',
      options: ['6 × 3', '6 × 6', '6 × 9', '6 × 12'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-18',
      type: QuestionType.multipleChoice,
      prompt: '65 + 25 = ?',
      options: ['80', '85', '90', '95'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-19',
      type: QuestionType.multipleChoice,
      prompt: '50 元買 30 元的東西，找回多少錢？',
      options: ['10 元', '20 元', '30 元', '80 元'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-20',
      type: QuestionType.multipleChoice,
      prompt: '下面哪一個長度最長？',
      options: ['30 公分', '1 公尺', '80 公分', '50 公分'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-21',
      type: QuestionType.multipleChoice,
      prompt: '2 × 7 = ?',
      options: ['9', '12', '14', '16'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-22',
      type: QuestionType.multipleChoice,
      prompt: '15 ÷ 3 = ?',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-23',
      type: QuestionType.multipleChoice,
      prompt: '80 + 20 = ?',
      options: ['90', '100', '1000', '10'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-24',
      type: QuestionType.multipleChoice,
      prompt: '分針從 12 走到 6，走了幾分鐘？',
      options: ['15 分', '20 分', '30 分', '45 分'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-25',
      type: QuestionType.multipleChoice,
      prompt: '1 公尺 等於 幾公分？',
      options: ['10', '50', '100', '1000'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-26',
      type: QuestionType.multipleChoice,
      prompt: '10 × 3 = ?',
      options: ['3', '13', '30', '300'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-27',
      type: QuestionType.multipleChoice,
      prompt: '4 + 4 + 4 可以寫成 4 × ?',
      options: ['1', '2', '3', '4'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-28',
      type: QuestionType.multipleChoice,
      prompt: '一條 12 公尺的繩子，剪成 4 等長的段，每段幾公尺？',
      options: ['2', '3', '4', '5'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-29',
      type: QuestionType.multipleChoice,
      prompt: '下面哪一個是「3 的倍數」？',
      options: ['10', '12', '13', '14'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-30',
      type: QuestionType.multipleChoice,
      prompt: '圓的直徑是半徑的幾倍？',
      options: ['1 倍', '1.5 倍', '2 倍', '3 倍'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-31',
      type: QuestionType.multipleChoice,
      prompt: '31 + 9 = ?',
      options: ['30', '39', '40', '41'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-32',
      type: QuestionType.multipleChoice,
      prompt: '1 年大約有幾個月？',
      options: ['10 個月', '11 個月', '12 個月', '13 個月'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-33',
      type: QuestionType.multipleChoice,
      prompt: '99 - 1 = ?',
      options: ['80', '90', '98', '100'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-34',
      type: QuestionType.multipleChoice,
      prompt: '邊一樣長的四個直角的圖形是？',
      options: ['長方形', '正三角形', '正方形', '圓形'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-35',
      type: QuestionType.multipleChoice,
      prompt: '7 × 4 = 28 也可以檢查成？',
      options: [
        '4 + 4 + 4',
        '7 + 7 + 7 + 7',
        '4 × 7 也可以',
        '7 - 4',
      ],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-36',
      type: QuestionType.multipleChoice,
      prompt: '半小時是幾分鐘？',
      options: ['20 分', '25 分', '30 分', '40 分'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-37',
      type: QuestionType.multipleChoice,
      prompt: '20 ÷ 4 = ?',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-38',
      type: QuestionType.multipleChoice,
      prompt: '6 × 6 = ?',
      options: ['12', '30', '36', '42'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-39',
      type: QuestionType.multipleChoice,
      prompt: '一個圓的「圓心」是什麼？',
      options: [
        '圓的邊上的點',
        '到圓上各點距離相等的中心點',
        '直徑的中點之一',
        '圓的角',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-40',
      type: QuestionType.multipleChoice,
      prompt: '2 小時 30 分 ＝ 幾分？',
      options: ['90 分', '120 分', '150 分', '180 分'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-41',
      type: QuestionType.multipleChoice,
      prompt: '1 到 9 的乘法，9×5 和 5×9 的積是？',
      options: ['不同', '相同 45', '0', '14'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-42',
      type: QuestionType.multipleChoice,
      prompt: '下面哪一個是「3 的倍數」但「不是 2 的倍數」？',
      options: ['6', '9', '10', '12'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-43',
      type: QuestionType.multipleChoice,
      prompt: '1 分＝ 幾秒？',
      options: ['10 秒', '30 秒', '60 秒', '100 秒'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-44',
      type: QuestionType.multipleChoice,
      prompt: '3 的 4 倍和 4 的 3 倍，兩邊的積是？',
      options: ['不一樣', '都是 12', '都是 7', '都是 1'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-45',
      type: QuestionType.multipleChoice,
      prompt: '42 - 19 = ?',
      options: ['19', '21', '23', '33'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m2-46',
      type: QuestionType.multipleChoice,
      prompt: '把「紅色積木」和「藍色積木」分開放，是在做什麼？',
      options: ['亂丟', '依顏色分類', '吃掉', '睡覺'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-47',
      type: QuestionType.multipleChoice,
      prompt: '調查班上最喜歡的水果，一個一個問完用「正」字記人數，這一步叫？',
      options: ['亂猜', '收集資料並記錄', '不記錄', '只問老師'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m2-48',
      type: QuestionType.multipleChoice,
      prompt: '分類後，想知道「哪一類最多」，下一步要？',
      options: ['不比較', '比較每一類數出的數量', '只選自己喜歡的', '亂寫數字'],
      correctIndex: 1,
    ),
  ],

  // ============ 數學 三年級 ============
  'math-3': [
    Question(
      id: 'rp-m3-01',
      type: QuestionType.multipleChoice,
      prompt: '125 + 237 = ?',
      options: ['352', '362', '372', '382'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m3-02',
      type: QuestionType.multipleChoice,
      prompt: '6 × 7 = ?',
      options: ['36', '40', '42', '48'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m3-03',
      type: QuestionType.multipleChoice,
      prompt: '24 ÷ 4 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m3-04',
      type: QuestionType.multipleChoice,
      prompt: '1/2 + 1/2 = ?',
      options: ['0', '1/4', '1/2', '1'],
      correctIndex: 3,
    ),
    Question(
      id: 'rp-m3-05',
      type: QuestionType.multipleChoice,
      prompt: '8 × 9 = ?',
      options: ['64', '72', '81', '88'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m3-06',
      type: QuestionType.multipleChoice,
      prompt: '300 - 125 = ?',
      options: ['165', '175', '185', '195'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m3-07',
      type: QuestionType.multipleChoice,
      prompt: '一打有幾個？',
      options: ['6', '10', '12', '24'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m3-08',
      type: QuestionType.multipleChoice,
      prompt: '45 ÷ 5 = ?',
      options: ['7', '8', '9', '10'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m3-09',
      type: QuestionType.multipleChoice,
      prompt: '1 公尺等於幾公分？',
      options: ['10', '50', '100', '1000'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m3-10',
      type: QuestionType.multipleChoice,
      prompt: '三角形三個內角的和是幾度？',
      options: ['90 度', '180 度', '270 度', '360 度'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m3-11',
      type: QuestionType.multipleChoice,
      prompt: '2/6 等於?',
      options: ['1/2', '1/3', '1/4', '1/6'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-m3-12',
      type: QuestionType.multipleChoice,
      prompt: '73 × 10 = ?',
      options: ['73', '703', '730', '7300'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m3-13',
      type: QuestionType.multipleChoice,
      prompt: '250 + 350 = ?',
      options: ['500', '550', '600', '650'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-m3-14',
      type: QuestionType.multipleChoice,
      prompt: '1 公斤等於幾公克？',
      options: ['10', '100', '500', '1000'],
      correctIndex: 3,
    ),
    Question(
      id: 'rp-m3-15',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個分數比 1/2 大？',
      options: ['1/4', '1/3', '3/4', '1/8'],
      correctIndex: 2,
    ),
  ],

  // ============ 國語 一年級 ============
  'chinese-1': [
    Question(
      id: 'rp-c1-01',
      type: QuestionType.multipleChoice,
      prompt: '「ㄓㄨㄛ」是哪一個字的注音？',
      options: ['桌', '座', '坐', '作'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-02',
      type: QuestionType.multipleChoice,
      prompt: '「我」的注音是？',
      options: ['ㄨㄛˇ', 'ㄨㄚˇ', 'ㄨˇ', 'ㄛˇ'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-03',
      type: QuestionType.multipleChoice,
      prompt: '「媽媽」的「媽」是幾個字？',
      options: ['1 個', '2 個', '3 個', '4 個'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-04',
      type: QuestionType.multipleChoice,
      prompt: '與「大」相反的字是？',
      options: ['多', '小', '高', '低'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-05',
      type: QuestionType.multipleChoice,
      prompt: '「山」字有幾畫？',
      options: ['2 畫', '3 畫', '4 畫', '5 畫'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-06',
      type: QuestionType.multipleChoice,
      prompt: '「火」字上面像什麼？',
      options: ['水滴', '火苗', '樹枝', '房子'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-07',
      type: QuestionType.multipleChoice,
      prompt: '「太陽」是白天出現還是晚上？',
      options: ['白天', '晚上', '半夜', '清晨只有'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-08',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個字是數字？',
      options: ['手', '三', '口', '心'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-09',
      type: QuestionType.multipleChoice,
      prompt: '「你好」的「好」，右邊的字是?',
      options: ['子', '女', '子和女', '口'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-10',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個字有「水」字旁？',
      options: ['河', '樹', '山', '鳥'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-11',
      type: QuestionType.multipleChoice,
      prompt: '「爸爸」和「媽媽」合起來叫?',
      options: ['家人', '朋友', '老師', '同學'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-12',
      type: QuestionType.multipleChoice,
      prompt: '「早安」是什麼時候說的？',
      options: ['早上', '中午', '晚上', '半夜'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-13',
      type: QuestionType.multipleChoice,
      prompt: '與「上」相反的是?',
      options: ['左', '下', '右', '中'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-14',
      type: QuestionType.multipleChoice,
      prompt: '「花」字裡面有哪個部首？',
      options: ['艹 (草頭)', '木', '水', '火'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-15',
      type: QuestionType.multipleChoice,
      prompt: '一個星期有幾天？',
      options: ['5 天', '6 天', '7 天', '8 天'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c1-16',
      type: QuestionType.multipleChoice,
      prompt: '「口」字像我們身體的哪裡？',
      options: ['眼睛', '嘴巴', '耳朵', '鼻子'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-17',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個字跟「天」有關？',
      options: ['雲', '海', '土', '魚'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-18',
      type: QuestionType.multipleChoice,
      prompt: '「讀書」的「讀」，注音是?',
      options: ['ㄉㄨˊ', 'ㄉㄨˇ', 'ㄊㄨˇ', 'ㄊㄨˋ'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-19',
      type: QuestionType.multipleChoice,
      prompt: '「看」字上面是什麼？',
      options: ['手', '眼', '口', '耳'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-20',
      type: QuestionType.multipleChoice,
      prompt: '「日」和「月」合起來是什麼字？',
      options: ['明', '昌', '晶', '暗'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-21',
      type: QuestionType.multipleChoice,
      prompt: '句號「。」通常放在什麼地方？',
      options: [
        '一句話說完、意思完整的地方',
        '只放在句首',
        '隨便放',
        '不能寫在課本裡',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-22',
      type: QuestionType.multipleChoice,
      prompt: '與「冷」意思接近相反的是？',
      options: ['高', '熱', '快', '小'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-23',
      type: QuestionType.multipleChoice,
      prompt: '「學校」的「校」，和下面哪一個有關？',
      options: ['木、建築或場所', '魚', '天氣', '飲食'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-24',
      type: QuestionType.multipleChoice,
      prompt: '讀兒歌時，可以注意什麼讓讀起來好聽？',
      options: [
        '隨便亂念',
        '聽一聽節奏、停頓，跟著讀',
        '越念越小聲到沒有',
        '只讀一個字',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-25',
      type: QuestionType.multipleChoice,
      prompt: '「我們一起讀課文」的「讀」在說什麼行為？',
      options: ['畫圖', '大聲或小聲看字念出聲', '睡覺', '跑步'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-26',
      type: QuestionType.multipleChoice,
      prompt: '圖畫和文字同時在說故事時，我們可以？',
      options: [
        '只看圖、也可以搭配文字理解',
        '圖沒用',
        '字都錯的',
        '不能同時看',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-27',
      type: QuestionType.multipleChoice,
      prompt: '「小」和「大」的關係是？',
      options: ['同意思', '常常當成相反的意思來比較', '不能一起出現', '是數字'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-28',
      type: QuestionType.multipleChoice,
      prompt: '有禮貌地向長輩說明「我來了」，用哪一個最合宜？',
      options: [
        '喂！我來囉很吵欸',
        '○○好，我來了',
        '不說話衝進去',
        '罵人',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-29',
      type: QuestionType.multipleChoice,
      prompt: '「筆劃要照順序」是為了？',
      options: [
        '亂寫沒關係',
        '幫助寫得清楚、以後寫得更快也好看',
        '不寫也沒關係',
        '寫多就錯',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-30',
      type: QuestionType.multipleChoice,
      prompt: '和「多」成對比、方向相反，常和「多」一組練習的詞是？',
      options: ['高', '少', '大', '長'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-31',
      type: QuestionType.multipleChoice,
      prompt: '看故事書時，遇到不認識的新字，第一步可以？',
      options: [
        '丟掉書本',
        '在生字本抄寫或請大人教一教',
        '亂讀亂念',
        '不看了',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-32',
      type: QuestionType.multipleChoice,
      prompt: '「學期」是什麼？',
      options: [
        '一個學年切成的上學期、下學期兩大段上課期間',
        '一天吃三次飯',
        '一節下課',
        '一個人',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-33',
      type: QuestionType.multipleChoice,
      prompt: '敘述「我早上、中午、晚上做了什麼」要注意？',
      options: [
        '亂寫沒有順序',
        '有時間的順序讀者比較懂',
        '只能寫早上',
        '只寫晚上',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-34',
      type: QuestionType.multipleChoice,
      prompt: '「兒歌」常常有什麼，讀起來很有節奏？',
      options: [
        '完全沒有重複',
        '韻腳、重覆的句型、節拍',
        '只能嘆氣',
        '只能念英文',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-35',
      type: QuestionType.multipleChoice,
      prompt: '「圖和文字都說故事」的閱讀，下面哪一個是對的？',
      options: [
        '兩邊有時互相補充、幫我們想得更完整',
        '只能選一邊看',
        '圖都錯的',
        '沒有字才是故事',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-36',
      type: QuestionType.multipleChoice,
      prompt: '寫作業前，我們可以先做什麼，字會寫得比較好？',
      options: [
        '拿筆亂劃不坐好',
        '紙筆就緒、坐姿、輕聲讀一題、想一想再寫',
        '一邊看電視一邊寫滿就對',
        '不寫',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-37',
      type: QuestionType.multipleChoice,
      prompt: '「人」的注音是？',
      options: ['ㄖㄣˊ', 'ㄖˋ', 'ㄕˊ', 'ㄌㄢˇ'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-38',
      type: QuestionType.multipleChoice,
      prompt: '讀圖加文字的讀本時，圖片通常有什麼幫助？',
      options: [
        '完全沒用',
        '幫我們想像場景、人物表情與劇情',
        '圖要蓋寫成績',
        '圖是印錯的',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-39',
      type: QuestionType.multipleChoice,
      prompt: '「學校」的「學」和什麼活動最有關？',
      options: ['睡覺', '讀書、寫功課、上課學本領', '亂丟垃圾', '不吃飯'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-40',
      type: QuestionType.multipleChoice,
      prompt: '我們說「學期」的時候，在聊什麼？',
      options: [
        '一個學年裡的「上學期、下學期」的其中一段上課時間',
        '一次點心時間',
        '一節 10 分鐘',
        '一個人',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-41',
      type: QuestionType.multipleChoice,
      prompt: '「兒歌大聲唱」時，下面哪一個是尊重別人的行為？',
      options: [
        '在圖書館大聲尖叫亂叫',
        '在練習、表演等合適的場合跟著老師的節奏',
        '拿麥克風故意尖叫',
        '亂丟紙團',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-42',
      type: QuestionType.multipleChoice,
      prompt: '「學校的一天」可以從幾點、做了什麼、心情如何來寫，是練什麼？',
      options: [
        '只學亂寫不寫字',
        '有順序的敘事與觀察',
        '不寫日期沒關係',
        '不可以用完整句',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-43',
      type: QuestionType.multipleChoice,
      prompt: '「圖＋文」的書，兩邊的關係是？',
      options: [
        '常常彼此告訴我們同一件事或互相補充',
        '永遠不一樣',
        '圖是假的不必看',
        '字是假的不必讀',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-44',
      type: QuestionType.multipleChoice,
      prompt: '我們練習「我會寫字」的時候，寫在田字或格子內是為了？',
      options: [
        '亂寫一氣沒有目的',
        '幫字的大小、筆劃有位置、整齊好看',
        '格子越小越好亂劃',
        '不用在格子裡',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-45',
      type: QuestionType.multipleChoice,
      prompt: '下面哪一個最適合寫在「生字本」裡？',
      options: [
        '剛學到的生字和注音，照老師教的方式練寫',
        '隨便亂畫的鬼畫符',
        '同學的簽名當成自己的',
        '不寫只帶空本子',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c1-46',
      type: QuestionType.multipleChoice,
      prompt: '同學在台上報告時，台下比較好的態度是？',
      options: [
        '大聲聊天蓋過他',
        '安靜聽、有需要再舉手發問',
        '低頭一直玩不抬頭',
        '嘲笑他講錯',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-47',
      type: QuestionType.multipleChoice,
      prompt: '「我覺得……因為……」這種說法可以幫助我們？',
      options: [
        '亂講不用理由',
        '把想法和理由說清楚',
        '不能用在課堂',
        '只能寫在考卷上',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c1-48',
      type: QuestionType.multipleChoice,
      prompt: '讀完故事後，哪一個比較像「讀懂內容的提問」？',
      options: [
        '主角為什麼要這樣做？',
        '今天便當有幾顆花椰菜？',
        '天空有幾朵雲？（與故事無關）',
        '不問問題比較好',
      ],
      correctIndex: 0,
    ),
  ],

  // ============ 國語 二年級 ============
  'chinese-2': [
    Question(
      id: 'rp-c2-01',
      type: QuestionType.multipleChoice,
      prompt: '「動物園」裡最不可能看到什麼？',
      options: ['獅子', '老虎', '電視機', '大象'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c2-02',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個字是「顏色」？',
      options: ['紅', '跑', '吃', '快'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-03',
      type: QuestionType.multipleChoice,
      prompt: '「又高又瘦」形容的是？',
      options: ['矮胖的人', '高瘦的人', '生氣的人', '生病的人'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-04',
      type: QuestionType.multipleChoice,
      prompt: '「春天」之後是?',
      options: ['夏天', '秋天', '冬天', '下雨天'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-05',
      type: QuestionType.multipleChoice,
      prompt: '「笑容滿面」是什麼心情？',
      options: ['傷心', '生氣', '開心', '害怕'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c2-06',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個是「交通工具」？',
      options: ['桌子', '汽車', '電視', '書本'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-07',
      type: QuestionType.multipleChoice,
      prompt: '「蘋果」是什麼？',
      options: ['動物', '水果', '花', '工具'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-08',
      type: QuestionType.multipleChoice,
      prompt: '「早」字上面是?',
      options: ['日', '月', '口', '木'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-09',
      type: QuestionType.multipleChoice,
      prompt: '「快樂」的反義詞是?',
      options: ['高興', '難過', '笑', '美麗'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-10',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個字有「月」部？',
      options: ['明', '山', '水', '石'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-11',
      type: QuestionType.multipleChoice,
      prompt: '「上學」和「放學」相反的是?',
      options: ['同義詞', '反義詞', '相同詞', '形容詞'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-12',
      type: QuestionType.multipleChoice,
      prompt: '「跑得很快」的「得」怎麼用？',
      options: ['助詞', '名詞', '動詞', '形容詞'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-13',
      type: QuestionType.multipleChoice,
      prompt: '「下雨天」我們要帶什麼出門？',
      options: ['扇子', '雨傘', '太陽眼鏡', '棉被'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-14',
      type: QuestionType.multipleChoice,
      prompt: '「小鳥飛上天」是什麼句型？',
      options: ['問句', '感嘆句', '敘述句', '命令句'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c2-15',
      type: QuestionType.multipleChoice,
      prompt: '「心」部的字大多和什麼有關？',
      options: ['水', '火', '心情', '動作'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c2-16',
      type: QuestionType.multipleChoice,
      prompt: '「端午節」是紀念哪位古人、也有龍舟與吃粽的節日？',
      options: ['屈原', '聖誕老人', '嫦娥', '關公'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-17',
      type: QuestionType.multipleChoice,
      prompt: '「圖畫小字典」主要幫我們？',
      options: [
        '亂丟不查',
        '不會的字的注音、簡單意思、還有圖可以對照',
        '睡覺',
        '不讀只玩',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-18',
      type: QuestionType.multipleChoice,
      prompt: '「我會用工具書」的態度，不應該？',
      options: [
        '亂丟、撕破圖書館的書或字典',
        '有禮地翻閱、輕聲在閱讀角查字',
        '不會先抄在生字本再問人',
        '在教室一起跟老師學部首、筆劃',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-19',
      type: QuestionType.multipleChoice,
      prompt: '「家鄉」的「鄉」常和什麼一起談，表示我成長、居住之處？',
      options: [
        '只有別人的家',
        '我們的故鄉、在地的社區、土地',
        '天上',
        '不認識的國家就當家鄉',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-20',
      type: QuestionType.multipleChoice,
      prompt: '「美麗臺灣」的觀點不應該？',
      options: [
        '亂丟垃圾、破壞生態、不尊重在地文化',
        '淨灘、維持步道整潔',
        '參觀在地的廟宇、博物館、自然步道',
        '學老師的介紹、認真聽導覽或故事',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-21',
      type: QuestionType.multipleChoice,
      prompt: '寫「自然觀察筆記」時，下列哪一項是「合理的開頭」？',
      options: [
        '寫上日期、地點、天氣與一兩行看到什麼',
        '亂劃一筆、沒有日期沒有字',
        '不寫只丟在泥土裡',
        '不要觀察直接抄別人筆記',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-22',
      type: QuestionType.multipleChoice,
      prompt: '戶外觀察小昆蟲或植物，應該？',
      options: [
        '亂採折、丟石頭、踩花圃',
        '不傷害、輕聲、保持距離，必要時有大人帶',
        '抓回家養死再丟棄',
        '搖樹亂丟飼料讓生態亂',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-23',
      type: QuestionType.multipleChoice,
      prompt: '與「尊重」有關的敘述，比較合理的是？',
      options: [
        '亂罵在地的風俗',
        '不嘲笑、願意聽說明與導覽、遵守規定',
        '亂丟在地的垃圾',
        '亂在古蹟亂劃自己名字',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-24',
      type: QuestionType.multipleChoice,
      prompt: '「學期回顧：我讀我寫我成長」是在提醒我們？',
      options: [
        '讀、寫不用練',
        '讀、寫常常練，能力與興趣會漸漸變好',
        '不跟大人分享學了什麼也沒關係',
        '只能考試不能說出來',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-25',
      type: QuestionType.multipleChoice,
      prompt: '跟家人分享「學年回顧」可以說什麼，比較有幫助？',
      options: [
        '兩本讀過的書＋一個學到的新字或好句子＋一個下學年想多練的習慣',
        '亂罵學校',
        '亂丟作業不給人看',
        '什麼都不回顧',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-26',
      type: QuestionType.multipleChoice,
      prompt: '「圖＋文」的招牌或海報在生活上幫我們？',
      options: [
        '完全沒有資訊',
        '圖、字一起傳遞地點、活動、要注意的事',
        '圖是印錯的',
        '只有英文才能看',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-27',
      type: QuestionType.multipleChoice,
      prompt: '讀兒歌裡的「重覆句」可以幫我們？',
      options: [
        '記節奏、預測、背誦、說一說好聽的地方',
        '亂亂讀不聽聲音',
        '兒歌不能讀大聲',
        '兒歌不能表演',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-28',
      type: QuestionType.multipleChoice,
      prompt: '「學校的一天」裡的「上課、下課、吃午餐、放學」是在說？',
      options: [
        '亂的沒有順序',
        '有時間上先後的經歷、可以寫敘事',
        '不存在的幻想',
        '不可以在作文裡寫出來',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-29',
      type: QuestionType.multipleChoice,
      prompt: '我們說臺灣「有山有海」的描寫，是什麼學習內容？',
      options: [
        '地理、自然與在地文化的認識',
        '亂亂的沒意思',
        '不可以在課本裡提',
        '不認字也可以隨便說',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-30',
      type: QuestionType.multipleChoice,
      prompt: '「學生」的「學」與學校、學習的關係是？',
      options: [
        '完全無關',
        '學＝學本領、讀書、聽老師的引導',
        '不寫不讀也可以',
        '亂丟學校物品',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-31',
      type: QuestionType.multipleChoice,
      prompt: '「圖＋文」的繪本或課本，兩邊的訊息可能？',
      options: [
        '完全相反不能一起讀',
        '圖、文一起補敘、幫讀者理解內容',
        '圖一定要假的',
        '文一定要刪光',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-32',
      type: QuestionType.multipleChoice,
      prompt: '「兒歌大聲唱」的「大聲」是說在什麼場合？',
      options: [
        '隨隨便便在需要安靜的圖書館亂叫',
        '在練習、上音樂、表演、老師帶的開口練讀的場合，清楚把字念出來',
        '一輩子都不開口',
        '只能說不能唱',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-33',
      type: QuestionType.multipleChoice,
      prompt: '「圖＋觀察筆記」的「圖畫＋幾行字」的組合，是為了？',
      options: [
        '亂亂的沒用',
        '幫讀者回想當下看到、感覺到什麼，訓練讀圖＋寫幾句話的表達',
        '圖是蓋在字上的，不要看',
        '圖是抄別人的不合法',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-34',
      type: QuestionType.multipleChoice,
      prompt: '「學到新的字＋學到新的讀法」的「注音＋寫在生字本」怎麼搭配比較好？',
      options: [
        '隨便寫亂丟、不讀不念',
        '讀一讀＋在格子裡照筆劃、照老師的範字練一練＋有時在句子裡造句',
        '亂丟不教',
        '亂丟不背',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-35',
      type: QuestionType.multipleChoice,
      prompt: '「一條一條把一天的事情排好」和「亂亂的」的差別是？',
      options: [
        '亂的比較像作文',
        '有時間順序、讀者才容易懂「誰、何時、做了什麼」',
        '故事不能有順序',
        '亂的才是故事',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-36',
      type: QuestionType.multipleChoice,
      prompt: '我們說「圖＋讀＋寫＋學到的生活經驗」一起是什麼？',
      options: [
        '國小國語綜合讀、說、寫、圖、文化與工具書的學習內容',
        '亂丟的',
        '跟國語沒有關係的',
        '亂丟的跟課本無關',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-37',
      type: QuestionType.multipleChoice,
      prompt: '圖＋學生討論時，我們主要練到什麼？',
      options: [
        '不聽同學說話、只自顧自玩',
        '讀圖的發現、聽人說、輪流提問，提升閱讀與口語表達',
        '討論時不開口、睡覺',
        '亂丟圖畫、撕書',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-38',
      type: QuestionType.multipleChoice,
      prompt: '讀圖時，角色的表情、動作幫我們推測？',
      options: [
        '圖是裝飾的，不用看',
        '心情、故事可能的衝突或轉折',
        '圖的顏色跟故事無關',
        '圖的角一定是直角',
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c2-39',
      type: QuestionType.multipleChoice,
      prompt: '「好幾幅圖排成有先後的順序」常常表示？',
      options: [
        '故事依照時間在發生',
        '亂亂的沒有劇情',
        '圖的張數是錯的',
        '圖的紙不合法',
      ],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c2-40',
      type: QuestionType.multipleChoice,
      prompt: '學年要結束時，跟家人、老師分享學到什麼，哪一個態度最合宜？',
      options: [
        '具體說出幾點學到什麼＋一個要改進的學習習慣、也說謝意',
        '亂罵、不說任何具體事',
        '胡說亂寫、不願負責任地分享',
        '完全沉默、什麼都不願意說',
      ],
      correctIndex: 0,
    ),
  ],

  // ============ 國語 三年級 ============
  'chinese-3': [
    Question(
      id: 'rp-c3-01',
      type: QuestionType.multipleChoice,
      prompt: '「溫故知新」的意思是?',
      options: [
        '做新的事',
        '複習舊的學到新的',
        '忘掉過去',
        '結交新朋友'
      ],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-02',
      type: QuestionType.multipleChoice,
      prompt: '「他跑得像風一樣快」用了什麼修辭？',
      options: ['譬喻', '擬人', '誇飾', '排比'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c3-03',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個成語形容非常開心？',
      options: ['愁眉苦臉', '眉開眼笑', '垂頭喪氣', '呆若木雞'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-04',
      type: QuestionType.multipleChoice,
      prompt: '「花開了」和「花謝了」是?',
      options: ['同義詞', '反義詞', '譬喻', '形容詞'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-05',
      type: QuestionType.multipleChoice,
      prompt: '「一隻隻」表示什麼？',
      options: ['一個', '很多個', '兩個', '沒有'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-06',
      type: QuestionType.multipleChoice,
      prompt: '「月亮」又叫什麼？',
      options: ['太陽', '嫦娥', '明月', '星星'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c3-07',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個是問句？',
      options: [
        '我吃飯了。',
        '今天天氣真好！',
        '你吃飯了嗎？',
        '請坐下。'
      ],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c3-08',
      type: QuestionType.multipleChoice,
      prompt: '「鳥兒在唱歌」用了什麼修辭？',
      options: ['譬喻', '擬人', '誇飾', '對偶'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-09',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個是動詞？',
      options: ['大', '跑', '紅', '快'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-10',
      type: QuestionType.multipleChoice,
      prompt: '「一年有幾個季節？」',
      options: ['2', '3', '4', '5'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c3-11',
      type: QuestionType.multipleChoice,
      prompt: '「書」的量詞是?',
      options: ['張', '本', '條', '顆'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-12',
      type: QuestionType.multipleChoice,
      prompt: '「三心二意」形容什麼？',
      options: ['專心', '不專心', '很聰明', '很勇敢'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-13',
      type: QuestionType.multipleChoice,
      prompt: '下面哪個不是四季？',
      options: ['春', '夏', '日', '秋'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c3-14',
      type: QuestionType.multipleChoice,
      prompt: '「笑」和「哭」是?',
      options: ['同義詞', '反義詞', '形容詞', '量詞'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c3-15',
      type: QuestionType.multipleChoice,
      prompt: '「一心一意」的意思?',
      options: ['猶豫不決', '專心做一件事', '想很多事', '不認真'],
      correctIndex: 1,
    ),
  ],

  // ============ 國語 四年級 ============
  'chinese-4': [
    Question(
      id: 'rp-c4-01',
      type: QuestionType.multipleChoice,
      prompt: '「畫蛇添足」的意思?',
      options: ['畫很美', '多餘的動作', '很會畫畫', '速度很快'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c4-02',
      type: QuestionType.multipleChoice,
      prompt: '「杯弓蛇影」形容?',
      options: ['想太多', '膽子大', '愛運動', '很誠實'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c4-03',
      type: QuestionType.multipleChoice,
      prompt: '「同甘共苦」的意思?',
      options: ['一起玩', '一起吃甜的', '好壞一起', '只吃苦的'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c4-04',
      type: QuestionType.multipleChoice,
      prompt: '「朗朗上口」形容?',
      options: ['唸得很順', '唸得很慢', '嘴巴很大', '唱歌很好'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c4-05',
      type: QuestionType.multipleChoice,
      prompt: '「白雲悠悠」用的修辭是?',
      options: ['疊字', '譬喻', '問句', '擬人'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c4-06',
      type: QuestionType.multipleChoice,
      prompt: '「張大嘴巴、瞪大眼睛」用了什麼修辭？',
      options: ['譬喻', '擬人', '誇飾', '排比'],
      correctIndex: 3,
    ),
    Question(
      id: 'rp-c4-07',
      type: QuestionType.multipleChoice,
      prompt: '「天高地厚」出自哪種文體？',
      options: ['詩', '小說', '成語', '散文'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c4-08',
      type: QuestionType.multipleChoice,
      prompt: '「作家」的「家」是什麼意思？',
      options: ['家庭', '專長的人', '家具', '家裡'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c4-09',
      type: QuestionType.multipleChoice,
      prompt: '下列哪個是形容詞？',
      options: ['美麗', '吃飯', '書本', '學校'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-c4-10',
      type: QuestionType.multipleChoice,
      prompt: '「千山萬水」描寫?',
      options: ['很近', '很遠很多', '下雨', '在山上'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c4-11',
      type: QuestionType.multipleChoice,
      prompt: '「無微不至」形容照顧?',
      options: ['很少', '很周到', '很粗心', '沒照顧'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c4-12',
      type: QuestionType.multipleChoice,
      prompt: '「孜孜不倦」形容?',
      options: ['很累', '很勤勞', '很懶', '很慢'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c4-13',
      type: QuestionType.multipleChoice,
      prompt: '「馬到成功」用在?',
      options: ['失敗時', '開始前的祝福', '生病時', '吃飯時'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-c4-14',
      type: QuestionType.multipleChoice,
      prompt: '「滴水穿石」比喻?',
      options: ['水很多', '力量很大', '持之以恆', '冷得結冰'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-c4-15',
      type: QuestionType.multipleChoice,
      prompt: '「百聞不如一見」的意思?',
      options: [
        '聽到很多次',
        '親眼看到才真實',
        '不用看',
        '看一百次'
      ],
      correctIndex: 1,
    ),
  ],

  // ============ 英語 一年級 ============
  'english-1': [
    Question(
      id: 'rp-e1-01',
      type: QuestionType.multipleChoice,
      prompt: '蘋果的英文是？',
      options: ['Banana', 'Apple', 'Orange', 'Grape'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e1-02',
      type: QuestionType.multipleChoice,
      prompt: '"Cat" 的中文意思是？',
      options: ['狗', '貓', '鳥', '魚'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e1-03',
      type: QuestionType.multipleChoice,
      prompt: '"Hello" 怎麼回應最好？',
      options: ['Hi', 'Cat', 'Red', 'Book'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e1-04',
      type: QuestionType.multipleChoice,
      prompt: '紅色的英文是？',
      options: ['Blue', 'Green', 'Red', 'Yellow'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-e1-05',
      type: QuestionType.multipleChoice,
      prompt: '"One" 是多少？',
      options: ['1', '2', '3', '4'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e1-06',
      type: QuestionType.multipleChoice,
      prompt: '"Three" 是多少？',
      options: ['1', '2', '3', '4'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-e1-07',
      type: QuestionType.multipleChoice,
      prompt: '"Dog" 的中文意思？',
      options: ['貓', '狗', '豬', '牛'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e1-08',
      type: QuestionType.multipleChoice,
      prompt: '書本的英文是?',
      options: ['Book', 'Pen', 'Desk', 'Chair'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e1-09',
      type: QuestionType.multipleChoice,
      prompt: '"Good morning" 什麼時候說？',
      options: ['早上', '中午', '晚上', '睡前'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e1-10',
      type: QuestionType.multipleChoice,
      prompt: '"Thank you" 是什麼意思？',
      options: ['對不起', '謝謝', '你好', '再見'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e1-11',
      type: QuestionType.multipleChoice,
      prompt: '"Water" 是?',
      options: ['水', '火', '風', '土'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e1-12',
      type: QuestionType.multipleChoice,
      prompt: '"Bye" 是什麼意思？',
      options: ['你好', '再見', '謝謝', '對不起'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e1-13',
      type: QuestionType.multipleChoice,
      prompt: '"Fish" 是?',
      options: ['魚', '肉', '菜', '飯'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e1-14',
      type: QuestionType.multipleChoice,
      prompt: '"Five" 是多少?',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-e1-15',
      type: QuestionType.multipleChoice,
      prompt: '香蕉的英文是?',
      options: ['Apple', 'Banana', 'Mango', 'Lemon'],
      correctIndex: 1,
    ),
  ],

  // ============ 英語 二年級 ============
  'english-2': [
    Question(
      id: 'rp-e2-01',
      type: QuestionType.multipleChoice,
      prompt: '"I am happy" 是什麼意思?',
      options: ['我很累', '我很開心', '我很餓', '我很冷'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-02',
      type: QuestionType.multipleChoice,
      prompt: '"What color is it?" 問的是?',
      options: ['什麼顏色', '什麼形狀', '多大', '多少錢'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e2-03',
      type: QuestionType.multipleChoice,
      prompt: '"How old are you?" 回答應是?',
      options: ['Eight', 'Blue', 'Apple', 'Monday'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e2-04',
      type: QuestionType.multipleChoice,
      prompt: '"Monday" 是?',
      options: ['星期一', '星期二', '星期日', '星期六'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e2-05',
      type: QuestionType.multipleChoice,
      prompt: '"Mother" 的意思?',
      options: ['爸爸', '媽媽', '哥哥', '姊姊'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-06',
      type: QuestionType.multipleChoice,
      prompt: '"Pencil" 是?',
      options: ['鉛筆', '橡皮擦', '尺', '書包'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-e2-07',
      type: QuestionType.multipleChoice,
      prompt: '"Ten" 是多少?',
      options: ['5', '10', '15', '20'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-08',
      type: QuestionType.multipleChoice,
      prompt: '"I like..." 後面通常接?',
      options: ['動詞', '名詞', '問號', '句號'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-09',
      type: QuestionType.multipleChoice,
      prompt: '"Sunny" 是什麼天氣?',
      options: ['下雨', '晴天', '下雪', '刮風'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-10',
      type: QuestionType.multipleChoice,
      prompt: '"I\'m sorry" 是?',
      options: ['謝謝', '對不起', '再見', '你好'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-11',
      type: QuestionType.multipleChoice,
      prompt: '"Rabbit" 是?',
      options: ['老鼠', '兔子', '松鼠', '狐狸'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-12',
      type: QuestionType.multipleChoice,
      prompt: '"School" 是?',
      options: ['公園', '學校', '醫院', '家'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-13',
      type: QuestionType.multipleChoice,
      prompt: '"Friend" 是?',
      options: ['敵人', '朋友', '家人', '老師'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-e2-14',
      type: QuestionType.multipleChoice,
      prompt: '"Milk" 是?',
      options: ['水', '果汁', '牛奶', '茶'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-e2-15',
      type: QuestionType.multipleChoice,
      prompt: '"Run" 是?',
      options: ['走', '跑', '跳', '坐'],
      correctIndex: 1,
    ),
  ],

  // ============ 自然 通用 ============
  'science-1': [
    Question(
      id: 'rp-s1-01',
      type: QuestionType.multipleChoice,
      prompt: '下列哪個是植物？',
      options: ['狗', '小草', '鳥', '魚'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-02',
      type: QuestionType.multipleChoice,
      prompt: '太陽從哪邊升起？',
      options: ['東', '西', '南', '北'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-s1-03',
      type: QuestionType.multipleChoice,
      prompt: '哪一個季節會下雪？',
      options: ['春天', '夏天', '秋天', '冬天'],
      correctIndex: 3,
    ),
    Question(
      id: 'rp-s1-04',
      type: QuestionType.multipleChoice,
      prompt: '植物成長需要什麼？',
      options: ['只要水', '陽光、水和空氣', '只要土', '只要肥料'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-05',
      type: QuestionType.multipleChoice,
      prompt: '下列何者不是昆蟲？',
      options: ['螞蟻', '蜜蜂', '蜘蛛', '蝴蝶'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-s1-06',
      type: QuestionType.multipleChoice,
      prompt: '水的三種狀態不包括?',
      options: ['冰', '水', '木', '水蒸氣'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-s1-07',
      type: QuestionType.multipleChoice,
      prompt: '月亮繞著什麼轉？',
      options: ['太陽', '地球', '火星', '月亮不會轉'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-08',
      type: QuestionType.multipleChoice,
      prompt: '下列哪個是哺乳類？',
      options: ['魚', '鳥', '蛇', '貓'],
      correctIndex: 3,
    ),
    Question(
      id: 'rp-s1-09',
      type: QuestionType.multipleChoice,
      prompt: '磁鐵不會吸什麼？',
      options: ['鐵釘', '木頭', '迴紋針', '螺絲'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-10',
      type: QuestionType.multipleChoice,
      prompt: '我們用哪個器官聽聲音？',
      options: ['眼睛', '耳朵', '鼻子', '嘴巴'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-11',
      type: QuestionType.multipleChoice,
      prompt: '照顧小盆栽時，哪一個比較適當？',
      options: ['每天狂澆水', '完全不澆水', '適量澆水', '用汽水澆'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-s1-12',
      type: QuestionType.multipleChoice,
      prompt: '「小樹」比較屬於哪一類？',
      options: ['植物', '礦物', '塑膠', '雲'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-s1-13',
      type: QuestionType.multipleChoice,
      prompt: '冰塊在室溫下慢慢變小，多半變成？',
      options: ['沙子', '水', '火', '石頭'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-14',
      type: QuestionType.multipleChoice,
      prompt: '「觀察」的意思比較接近？',
      options: ['亂猜', '仔細看並記錄', '大聲唱歌', '睡覺'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-15',
      type: QuestionType.multipleChoice,
      prompt: '下雨天出門，比較需要？',
      options: ['雪球', '雨傘或雨衣', '滑雪板', '沙灘球'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-16',
      type: QuestionType.multipleChoice,
      prompt: '下列哪一個比較像節約用水？',
      options: ['刷牙時水一直開很大', '擦肥皂時先關水', '玩水槍不關', '一直放水玩'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-17',
      type: QuestionType.multipleChoice,
      prompt: '看太陽時，哪一個比較安全？',
      options: ['直視太陽比賽', '不直視，必要時用安全方式觀測', '用望遠鏡直看太陽', '盯著太陽不眨眼'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-18',
      type: QuestionType.multipleChoice,
      prompt: '資源回收的目的比較接近？',
      options: ['讓垃圾變多', '減少浪費、可再利用', '不用分類', '亂丟就好'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-s1-19',
      type: QuestionType.multipleChoice,
      prompt: '「白天」和「夜晚」差很多的是？',
      options: ['天空亮度與活動方式', '完全沒差別', '白天沒有太陽', '夜晚一定下雪'],
      correctIndex: 0,
    ),
    Question(
      id: 'rp-s1-20',
      type: QuestionType.multipleChoice,
      prompt: '在公園看到野鳥，比較好的做法是？',
      options: ['大聲嚇牠', '遠遠安靜觀察', '抓回家', '丟石頭'],
      correctIndex: 1,
    ),
  ],

  // ============ 社會 通用 ============
  'social-1': [
    Question(
      id: 'rp-so1-01',
      type: QuestionType.multipleChoice,
      prompt: '紅綠燈的紅燈代表?',
      options: ['可以走', '停下來', '慢慢走', '快跑'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-so1-02',
      type: QuestionType.multipleChoice,
      prompt: '打 110 是找誰?',
      options: ['救護車', '警察', '消防員', '醫生'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-so1-03',
      type: QuestionType.multipleChoice,
      prompt: '打 119 是找誰?',
      options: ['警察', '消防／救護', '家人', '老師'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-so1-04',
      type: QuestionType.multipleChoice,
      prompt: '我們住的國家是?',
      options: ['日本', '中華民國 (台灣)', '韓國', '美國'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-so1-05',
      type: QuestionType.multipleChoice,
      prompt: '行人過馬路要走?',
      options: ['馬路中間', '斑馬線', '車道', '任何地方'],
      correctIndex: 1,
    ),
    Question(
      id: 'rp-so1-06',
      type: QuestionType.multipleChoice,
      prompt: '下列哪個是國家元首?',
      options: ['市長', '校長', '總統', '班長'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-so1-07',
      type: QuestionType.multipleChoice,
      prompt: '在圖書館應該?',
      options: ['大聲說話', '跑來跑去', '輕聲細語', '吃東西'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-so1-08',
      type: QuestionType.multipleChoice,
      prompt: '下列哪項是公共場所應有的禮儀?',
      options: ['亂丟垃圾', '插隊', '排隊等候', '大聲喧嘩'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-so1-09',
      type: QuestionType.multipleChoice,
      prompt: '台灣首都是?',
      options: ['高雄', '台中', '台北', '台南'],
      correctIndex: 2,
    ),
    Question(
      id: 'rp-so1-10',
      type: QuestionType.multipleChoice,
      prompt: '看到受傷的同學應該?',
      options: ['不管', '取笑他', '告訴老師幫忙', '踢他一腳'],
      correctIndex: 2,
    ),
  ],
};

/// 取得學科×年級的延伸題庫；若該年級沒有，會回退到最接近的年級。
List<Question> getReviewPool(String subjectId, int grade) {
  final exact = kReviewPool[_key(subjectId, grade)];
  if (exact != null) return exact;

  // 找同學科最接近的年級
  int? bestGrade;
  int bestDist = 999;
  for (final k in kReviewPool.keys) {
    final parts = k.split('-');
    if (parts.length != 2) continue;
    final sid = parts[0];
    final g = int.tryParse(parts[1]) ?? -1;
    if (sid == subjectId) {
      final d = (g - grade).abs();
      if (d < bestDist) {
        bestDist = d;
        bestGrade = g;
      }
    }
  }
  if (bestGrade != null) {
    return kReviewPool[_key(subjectId, bestGrade)] ?? const [];
  }
  return const [];
}
