import '../../models/lesson.dart';
import '../../models/question.dart';

/// 國語課程（國小 1–4 年級，上下學期）
///
/// **108 課綱國語文**：低年級著重注音、識字與寫字、閱讀、寫作（口述／仿寫）；
/// 小一／小二以下單元主題、學期分段與《十二年國教課程綱要》學習內容對應，不依特定版本教科書。
const List<Lesson> kChineseLessons = [
  // ======== 一年級 上學期（首冊：注音符號 + 基礎識字）========
  Lesson(
    id: 'cl-c-1-1-u1',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 1,
    title: '上學了',
    summary: '認識聲母 ㄅㄆㄇㄈ',
    content: '新學期開始，我要上學了！\n\n先來認識第一組聲母：\nㄅ 不 ㄆ 皮 ㄇ 毛 ㄈ 飛\n\n試著跟著老師一起念，找找看生活中有哪些字是用這些聲母開頭的。',
    estimatedMinutes: 10,
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「爸爸」的「爸」開頭是哪個注音？',
        options: ['ㄅ', 'ㄆ', 'ㄇ', 'ㄈ'],
        correctIndex: 0,
        explanation: '爸 ㄅㄚˋ，開頭是 ㄅ。',
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一個字是 ㄇ 開頭？',
        options: ['飛', '皮', '貓', '不'],
        correctIndex: 2,
        explanation: '貓 ㄇㄠ，開頭是 ㄇ。',
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-1-u2',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 2,
    title: '我的家',
    summary: '認識聲母 ㄉㄊㄋㄌ',
    content: '家是溫暖的地方。\n\nㄉ 弟 ㄊ 湯 ㄋ 奶 ㄌ 來\n\n家人：爸爸、媽媽、弟弟、姊姊。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「弟弟」的「弟」用哪個聲母？',
        options: ['ㄉ', 'ㄊ', 'ㄋ', 'ㄌ'],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「奶奶」的開頭是？',
        options: ['ㄌ', 'ㄋ', 'ㄊ', 'ㄉ'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-1-u3',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 3,
    title: '動物朋友',
    summary: '認識韻母 ㄚㄛㄜㄝ',
    content: '動物園裡好熱鬧！\n\nㄚ 啊 ㄛ 喔 ㄜ 鵝 ㄝ 耶\n\n鴨、馬、鵝都在玩。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「鴨」的韻母是？',
        options: ['ㄚ', 'ㄛ', 'ㄜ', 'ㄝ'],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「哥哥」的韻母是？',
        options: ['ㄚ', 'ㄛ', 'ㄜ', 'ㄝ'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-1-u4',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 4,
    title: '小小的我',
    summary: '結合韻母練習：ㄞㄟㄠㄡ',
    content: '我會自己穿衣服、自己吃飯。\n\nㄞ 愛 ㄟ 飛 ㄠ 老 ㄡ 狗\n\n「小」＝ ㄒ＋ㄧ＋ㄠˇ',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「老師」的「老」韻母是？',
        options: ['ㄞ', 'ㄟ', 'ㄠ', 'ㄡ'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-1-u5',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 5,
    title: '好朋友',
    summary: '識字：手、口、耳、目',
    content: '我有一雙小小的手，可以寫字、畫畫。\n我有一個大大的口，可以唱歌、說話。\n我有兩個耳朵聽聲音，兩個眼睛看世界。\n\n【手】【口】【耳】【目】',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '用來寫字的是？',
        options: ['口', '目', '手', '耳'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「目」代表身體的哪個部位？',
        options: ['耳朵', '眼睛', '嘴巴', '手'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-1-u6',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 6,
    title: '我會寫字',
    summary: '筆劃與寫字習慣',
    content:
        '寫字前，身體坐正、紙放正。\n先「看字」再「寫字」：注意筆劃是橫是豎、先寫哪一筆。\n一筆一畫慢慢寫，不急躁。\n\n學習寫字：一、工、人',
    estimatedMinutes: 10,
    objectives: [
      '能說出寫字前應保持的坐姿與執筆要領',
      '能觀察範字再仿寫簡單單字',
    ],
    keyPoints: [
      '由左而右、由上而下的書寫習慣',
      '先寫大格再寫小格，保持字距',
    ],
    vocabulary: [
      VocabItem(term: '筆劃', meaning: '寫一個筆的動作', example: '一橫一豎是兩劃'),
      VocabItem(term: '坐姿', meaning: '坐著的姿勢', example: '要抬頭坐正'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '寫字前，我們應該怎麼坐？',
        options: ['趴著寫比較快', '身體坐正、紙本放正', '站著寫比較帥', '躺著寫'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「一」要怎麼寫比較常見的筆劃？',
        options: ['一豎', '一橫', '一圈', '一點就結束'],
        correctIndex: 1,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '寫完字，練習冊要怎麼辦？',
        options: ['丟在地板', '收好或交給老師', '撕掉', '藏起來'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-1-u7',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 7,
    title: '圖畫和文字',
    summary: '圖文閱讀的樂趣',
    content:
        '一本圖畫書裡有「圖畫」也有「文字」。\n我們可以先看圖，猜猜故事；\n再讀文字，確認內容。\n\n問問自己：圖中的人物在說什麼、做什麼？',
    estimatedMinutes: 9,
    objectives: [
      '能說出圖畫和文字在書中的不同功能',
      '能依圖文線索敘述簡單內容',
    ],
    keyPoints: [
      '讀圖是閱讀的開始；文字幫我們讀出完整意思',
      '讀完可以想想「我喜歡哪一段」',
    ],
    vocabulary: [
      VocabItem(term: '圖畫', meaning: '用畫的圖', example: '圖畫裡的兔子'),
      VocabItem(term: '文字', meaning: '我們寫的國字或注音', example: '書上黑色的字'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '圖畫和文字有什麼幫助？',
        options: [
          '只有文字最重要',
          '圖幫我們想像，字幫我們讀內容',
          '圖是拿來亂畫的',
          '沒有什麼幫助',
        ],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '看圖說故事時，可以問自己什麼？',
        options: [
          '天空有幾朵雲（亂算）',
          '人物在說什麼、做什麼',
          '圖的顏色一定錯的',
          '不許開口',
        ],
        correctIndex: 1,
      ),
    ],
  ),

  // ======== 一年級 下學期 ========
  Lesson(
    id: 'cl-c-1-2-u1',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 1,
    title: '春天來了',
    summary: '描寫春天景色',
    content: '春天來了，花兒開了，鳥兒叫了。\n草地綠綠的，蝴蝶飛呀飛。\n\n生字：春、花、鳥、草、飛',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '春天的草地是什麼顏色？',
        options: ['紅紅的', '黃黃的', '綠綠的', '黑黑的'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「蝴蝶飛呀飛」形容蝴蝶在做什麼？',
        options: ['休息', '飛翔', '吃花蜜', '睡覺'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-2-u2',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 2,
    title: '我會自己做',
    summary: '自理生活小文章',
    content: '我會自己穿衣服、自己刷牙、自己收玩具。\n長大了，我不再是小寶寶。\n\n生字：穿、刷、收、玩、寶',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '早上起床後應該？',
        options: ['再睡', '刷牙洗臉', '看電視', '吃糖果'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-2-u3',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 3,
    title: '雨下來了',
    summary: '認識標點符號與擬聲詞',
    content: '滴答！滴答！雨下來了。\n我撐著小雨傘，慢慢地走。\n水窪裡的小魚兒，對著我微笑。\n\n驚嘆號「！」表示驚喜或情緒。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「滴答！滴答！」是模仿什麼的聲音？',
        options: ['腳步聲', '雨聲', '鳥叫聲', '風聲'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-2-u4',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 4,
    title: '兒歌大聲唱',
    summary: '韻文與節奏感',
    content:
        '兒歌的句子常「短短亮亮」，有重複、好跟著念。\n例如：小星星、搖籃曲，都有重複的句子讓我們記得。\n\n我們可以拍子打節拍，一邊唸一邊聽重複的地方。',
    estimatedMinutes: 9,
    objectives: [
      '能聽出兒歌中重複的句子',
      '能跟著節拍朗讀簡短韻文',
    ],
    keyPoints: [
      '韻文幫助記憶與感受語感',
      '大聲念、小聲念，都是閱讀',
    ],
    vocabulary: [
      VocabItem(term: '兒歌', meaning: '給兒童唱或念的歌', example: '童謠兒歌'),
      VocabItem(term: '節奏', meaning: '有規律的長短快慢', example: '打拍子有節奏'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '兒歌常常有什麼特色？',
        options: [
          '句子都超長、字很難',
          '有重複、好記好跟念',
          '沒有聲音',
          '只能寫不能念',
        ],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '讀兒歌時，可以怎麼幫助節奏？',
        options: [
          '閉嘴不讀',
          '用手輕打拍子',
          '亂丟課本',
          '不聽老師帶讀',
        ],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-2-u5',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 5,
    title: '學校的一天',
    summary: '從上學到放學',
    content:
        '早上，我和同學說早；\n上課專心聽講、下課和好朋友玩遊戲；\n中午，跟老師、同學吃營養午餐；\n放學前，整理書包、說再見。',
    estimatedMinutes: 10,
    objectives: [
      '能依序說出上學到放學的主要活動',
      '能使用「先…再…」的簡單順序敘述',
    ],
    keyPoints: [
      '時間的「先後」是敘寫的線索',
      '禮貌問候是日常溝通的重要一環',
    ],
    vocabulary: [
      VocabItem(term: '專心', meaning: '注意力在一件事上', example: '專心聽講'),
      VocabItem(term: '營養', meaning: '幫身體成長的養分', example: '營養午餐'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '在學校「上課」通常要做什麼？',
        options: [
          '專心聽老師講解',
          '一聲不響不互動',
          '睡覺就好',
          '亂丟作業',
        ],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「下課」和「上課」的順序，常見的是？',
        options: [
          '先上課再下課',
          '沒有順序',
          '下課永遠不會上課',
          '一進教室就下課',
        ],
        correctIndex: 0,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '放學前應該要？',
        options: [
          '書包丟學校不管',
          '整理物品、和師長道別',
          '亂拿別人東西',
          '不跟老師說就離校',
        ],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-1-2-u6',
    subjectId: 'chinese',
    grade: 1,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 6,
    title: '我會聽與說',
    summary: '專心聽、輪流說、簡單提問',
    content:
        '上課時「聽」：眼睛看說話的人、不打斷別人、聽完再舉手。\n「說」：用完整句子回答，例如「我覺得……因為……」。\n讀完一小段故事，可以問：「主角遇到什麼困難？」「接下來可能會怎麼做？」',
    estimatedMinutes: 10,
    objectives: [
      '能練習專注聆聽與輪流發言',
      '能就讀本提出一個簡單問題或說出一句感想',
    ],
    keyPoints: [
      '聽與說是口語溝通與閱讀理解的起點',
      '問「為什麼、然後呢」幫助想得更深',
    ],
    vocabulary: [
      VocabItem(term: '專心聽', meaning: '把注意力放在說話內容上', example: '聽同學報告'),
      VocabItem(term: '提問', meaning: '把不懂或好奇的用問句說出來', example: '為什麼會下雨？'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '別人發言時，比較好的做法是？',
        options: [
          '大聲插嘴打斷',
          '安靜聽完，有需要再舉手',
          '低頭玩東西',
          '跟旁邊同學聊天',
        ],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「我覺得……因為……」這種說法是在？',
        options: [
          '亂講話',
          '說出自己的想法並給一個理由',
          '不能用在課堂',
          '只能寫不能說',
        ],
        correctIndex: 1,
      ),
      Question(
        id: 'q3',
        type: QuestionType.multipleChoice,
        prompt: '讀完故事後，哪一個是「好的提問」？',
        options: [
          '主角後來怎麼解決問題？',
          '午餐吃什麼？（與故事無關）',
          '不問問題',
          '亂猜結局不聽別人說',
        ],
        correctIndex: 0,
      ),
    ],
  ),

  // ======== 二年級 上學期 ========
  Lesson(
    id: 'cl-c-2-1-u1',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 1,
    title: '我升上二年級',
    summary: '新學期的心情',
    content: '暑假過完了，我升上二年級。\n學校裡有新老師、新同學，還有新的課本。\n我要更用心學習，幫助學弟學妹。\n\n生字：升、暑、課、用、幫',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「升上二年級」是什麼意思？',
        options: ['考試', '年級變高', '換學校', '放假'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '學姊應該如何對待學弟學妹？',
        options: ['不理他們', '嘲笑他們', '幫助他們', '躲開他們'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-1-u2',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 2,
    title: '有朋友真好',
    summary: '朋友之間的相處',
    content: '下課時，我和小華一起跳繩；\n上課時，我和小明一起討論。\n有朋友真好，我們互相幫忙、互相分享。\n\n生字：繩、論、互、忙、享',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「互相幫忙」中的「互相」是什麼意思？',
        options: ['只有一個人', '你幫我我幫你', '不用幫', '自己做'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-1-u3',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 3,
    title: '動物的家',
    summary: '動物棲息地介紹',
    content: '鳥兒的家在樹上，那叫作鳥巢。\n魚兒的家在水裡，那叫作河流。\n蜜蜂住在蜂巢裡，小狗住在狗屋裡。\n每種動物都有自己舒適的家。\n\n生字：巢、流、蜂、屋、適',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '鳥兒的家叫什麼？',
        options: ['狗屋', '鳥巢', '蜂巢', '河流'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '蜜蜂住在哪裡？',
        options: ['樹上', '水裡', '蜂巢', '洞穴'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-1-u4',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 4,
    title: '閱讀的樂趣',
    summary: '從書本認識世界',
    content: '書是我的好朋友。\n翻開書本，我可以到山上看日出，\n到海邊聽浪花，到古時候看歷史。\n多閱讀，知識就像滾雪球，越滾越大。\n\n生字：翻、浪、歷、識、雪',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「知識像滾雪球」比喻什麼？',
        options: ['越來越少', '越來越多', '會融化', '會變冷'],
        correctIndex: 1,
        explanation: '滾雪球會越滾越大，比喻知識會累積。',
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-1-u5',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 5,
    title: '我會用工具書',
    summary: '圖畫小字典的用法',
    content:
        '遇到不會讀、不太懂意思的字，可以查「圖畫小字典」或紙本字典：\n先找部首，再點筆劃，找到字卡上的注音和意思。\n學校圖書館的書，也可以請老師幫我們一起找關鍵字。',
    estimatedMinutes: 10,
    objectives: [
      '知道遇到生字可以請教大人或使用工具書',
      '能配合部首、筆劃找到簡單字彙的說明',
    ],
    keyPoints: [
      '不會的字先學著「寫在生字本、問清楚」',
      '閱讀是慢慢累積，不用一次全記住',
    ],
    vocabulary: [
      VocabItem(term: '部首', meaning: '字典歸類用的表意偏旁', example: '氵跟水有關'),
      VocabItem(term: '字典', meaning: '查注音、字義的工具書', example: '圖畫小字典'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '不會讀一個新字，第一步可以？',
        options: [
          '亂猜也不問人',
          '寫在生字本，請教老師或查字典',
          '不讀了',
          '丟到垃圾桶',
        ],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '圖畫小字典有什麼幫助？',
        options: [
          '讓圖幫我們分辨意思',
          '圖是拿來亂畫的',
          '圖讓我們不識字',
          '圖讓我們睡覺',
        ],
        correctIndex: 0,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-1-u6',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 6,
    title: '美麗臺灣',
    summary: '家鄉的自然與人文',
    content:
        '臺灣有山、有海、有美麗的農村與熱鬧的都市。\n不論我住哪一個鄉鎮，都可以說一說家附近的公園、廟宇或海邊。\n尊重不同地方的習慣，也是愛臺灣的表現。',
    estimatedMinutes: 10,
    objectives: [
      '能就生活經驗描述家鄉的一兩處地景或活動',
      '能說出尊重家鄉與不同社區的態度',
    ],
    keyPoints: [
      '從地圖或照片認識「我的家在哪裡」',
      '愛鄉、愛土地可以從小小行動開始',
    ],
    vocabulary: [
      VocabItem(term: '家鄉', meaning: '自己成長、居住的地方', example: '我的家鄉在臺中'),
      VocabItem(term: '尊重', meaning: '不輕慢、不嘲笑', example: '尊重不同文化'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '我們可以從什麼認識家鄉？',
        options: [
          '都不去外面看看',
          '圖畫、照片、實地走訪',
          '亂丟垃圾',
          '不跟大人說話',
        ],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「美麗臺灣」的態度不應該？',
        options: [
          '亂丟廢棄物破壞環境',
          '參加淨灘、維持整潔',
          '愛護生態',
          '學校介紹在地文化時用心聽',
        ],
        correctIndex: 0,
      ),
    ],
  ),

  // ======== 二年級 下學期 ========
  Lesson(
    id: 'cl-c-2-2-u1',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 1,
    title: '家的溫暖',
    summary: '家人的愛',
    content: '爸爸為我撐傘，媽媽為我煮飯，\n哥哥陪我玩，姊姊教我寫字。\n家，是我溫暖的小窩。\n\n生字：撐、煮、陪、窩、暖',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '課文中描述「家」是什麼？',
        options: ['冰冷的地方', '溫暖的小窩', '遙遠的夢', '黑色的洞'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-2-u2',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 2,
    title: '大自然的色彩',
    summary: '描寫自然景色',
    content: '藍藍的天空，白白的雲，\n綠綠的草地，紅紅的花朵。\n大自然是最棒的畫家，\n用顏色畫出美麗的世界。\n\n形容詞疊字：藍藍的、白白的、綠綠的',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '作者把大自然比喻成什麼？',
        options: ['老師', '畫家', '歌手', '醫生'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一個是疊字形容詞？',
        options: ['跑步', '綠綠的', '明天', '一個'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-2-u3',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 3,
    title: '端午節',
    summary: '認識傳統節慶',
    content: '五月五，慶端午，\n家家戶戶包粽子。\n立雞蛋、賽龍舟，\n掛香包、避邪氣。\n\n端午節是為了紀念詩人屈原。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '端午節是紀念哪一位古人？',
        options: ['李白', '屈原', '杜甫', '孔子'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一個「不是」端午節的習俗？',
        options: ['包粽子', '賽龍舟', '放鞭炮', '掛香包'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-2-u4',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 4,
    title: '自然觀察筆記',
    summary: '用眼睛與筆留下發現',
    content:
        '到公園、校園或陽台，看看植物怎麼長、小蟲怎麼活動；\n把日期、地點、天氣和看到的一兩件小事寫下來，就是「觀察筆記」。\n圖畫加幾句話，可以幫我們以後回憶當天的心情。',
    estimatedMinutes: 10,
    objectives: [
      '能簡要記錄觀察的時間、地點與重點',
      '能配合圖畫，用幾句話寫出心情或發現',
    ],
    keyPoints: [
      '觀察要專心、不傷害生物與植物',
      '寫的時候從「我看到／我聽到」開始，句子比較好接',
    ],
    vocabulary: [
      VocabItem(term: '觀察', meaning: '用感官仔細看、注意細節', example: '觀察雲的形狀'),
      VocabItem(term: '筆記', meaning: '把重點寫下來', example: '自然觀察筆記'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '寫觀察筆記，下列哪一項比較合適寫在開頭？',
        options: [
          '3 月 20 日，晴天，在學校中庭',
          '我很想吃冰',
          '亂亂的符號沒有日期',
          '不寫任何字只畫圈',
        ],
        correctIndex: 0,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '戶外觀察小昆蟲時，應該？',
        options: [
          '輕聲慢步、不隨意捕捉傷害',
          '大聲尖叫嚇走牠們',
          '用力踩扁',
          '丟石頭',
        ],
        correctIndex: 0,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-2-2-u5',
    subjectId: 'chinese',
    grade: 2,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 5,
    title: '學期回顧：我讀我寫我成長',
    summary: '整合閱讀、識字與表達',
    content:
        '這一學年我學了認字、讀兒歌與短故事、用完整句子說和寫，也認識節慶與家鄉。\n可以自己選一本喜歡的圖畫書，讀完後跟家人說「我喜歡的段落」與「一個學到的新字」。\n下一學年我們再一起讀更長的課文、寫更多小段落。',
    estimatedMinutes: 10,
    objectives: [
      '能舉出本學年學到的一兩項國語學習內容',
      '能簡要說出自己想再加強的閱讀或寫作習慣',
    ],
    keyPoints: [
      '學習是累積，慢慢來也可以進步很多',
      '讀和寫都要「多練、多說、多聽好故事」',
    ],
    vocabulary: [
      VocabItem(term: '回顧', meaning: '回想過去這段期間的經歷', example: '學期回顧'),
      VocabItem(term: '成長', meaning: '學到更多、變得更能做一件事', example: '閱讀成長'),
    ],
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '學期回顧時，下列哪一種表達有幫助？',
        options: [
          '只說「我討厭讀書」不說原因',
          '說出兩本自己讀過的書，以及印象最深的字或句子',
          '亂罵同學',
          '不跟大人分享',
        ],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「我讀我寫我成長」在提醒我們？',
        options: [
          '讀、寫要常常練，能力會慢慢變好',
          '讀了就不用寫',
          '寫了就不用讀',
          '都可以不必練',
        ],
        correctIndex: 0,
      ),
    ],
  ),

  // ======== 三年級 上學期 ========
  Lesson(
    id: 'cl-c-3-1-u1',
    subjectId: 'chinese',
    grade: 3,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 1,
    title: '美麗的家園',
    summary: '描寫家鄉',
    content: '我的家鄉有青翠的山巒，清澈的溪流。\n早晨，鳥兒在樹梢歌唱；\n傍晚，夕陽為大地披上金色的外衣。\n\n生字：翠、澈、梢、傍、披',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「夕陽為大地披上金色的外衣」是什麼修辭？',
        options: ['譬喻', '擬人', '誇飾', '排比'],
        correctIndex: 1,
        explanation: '把太陽當作人會「披外衣」，這是擬人法。',
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-3-1-u2',
    subjectId: 'chinese',
    grade: 3,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 2,
    title: '中秋賞月',
    summary: '認識中秋節',
    content: '中秋節是農曆八月十五，是團圓的日子。\n晚上，全家人圍坐一起賞月、吃月餅、吃柚子。\n月亮又大又圓，就像媽媽慈祥的臉。\n\n詞語：團圓、慈祥、柚子、月餅',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '中秋節是農曆幾月幾日？',
        options: ['七月七日', '八月十五日', '九月九日', '十月十日'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「團圓」最接近的意思是？',
        options: ['散開', '一起', '跑走', '吵架'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-3-1-u3',
    subjectId: 'chinese',
    grade: 3,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 3,
    title: '烏鴉喝水',
    summary: '閱讀寓言故事',
    content: '很久以前，有一隻口渴的烏鴉，找到一個瓶子。\n瓶子裡有水，但水太少，烏鴉的嘴喝不到。\n烏鴉靈機一動，把石頭一顆顆丟進瓶子，水位慢慢升高，終於喝到水了。\n\n道理：遇到困難要動腦思考，就能找到方法。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '烏鴉用什麼方法喝到水？',
        options: ['敲破瓶子', '把瓶子倒過來', '丟石頭讓水升高', '等下雨'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '這個故事告訴我們？',
        options: ['動物很笨', '要動腦思考', '不要喝水', '烏鴉很壞'],
        correctIndex: 1,
      ),
    ],
  ),

  // ======== 三年級 下學期 ========
  Lesson(
    id: 'cl-c-3-2-u1',
    subjectId: 'chinese',
    grade: 3,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 1,
    title: '愛迪生的故事',
    summary: '認識發明家',
    content: '愛迪生小時候喜歡問問題，大家都覺得他很奇怪。\n長大後，他不怕失敗，試了一千多次，終於發明了電燈。\n他說：「天才是一分的天分加上九十九分的努力。」\n\n從愛迪生的故事我們學到：成功來自不斷的努力。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '愛迪生發明了什麼？',
        options: ['電話', '電燈', '電視', '電腦'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '愛迪生名言中，天才需要幾分努力？',
        options: ['一分', '五十分', '九十九分', '全部靠天分'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-3-2-u2',
    subjectId: 'chinese',
    grade: 3,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 2,
    title: '圖書館之旅',
    summary: '認識圖書館與閱讀',
    content: '今天老師帶我們參觀圖書館。\n一走進大門，書香撲鼻而來。\n書架上的書分類整齊：故事書、科學書、歷史書……\n只要用心翻閱，就能打開知識的大門。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「書香撲鼻而來」是什麼意思？',
        options: ['書發出香水味', '書的氣味很濃', '書很臭', '書會說話'],
        correctIndex: 1,
        explanation: '「書香」是文學上比喻書的氣味或知識氛圍。',
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-3-2-u3',
    subjectId: 'chinese',
    grade: 3,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 3,
    title: '螞蟻與蟋蟀',
    summary: '伊索寓言',
    content: '夏天，蟋蟀每天唱歌玩耍，螞蟻努力搬運食物。\n冬天來了，蟋蟀沒東西吃，又冷又餓；\n螞蟻家裡溫暖，糧食也充足。\n\n教訓：今天的努力，是為了明天的生活。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '這個寓言告訴我們？',
        options: ['夏天很熱', '要努力不懈', '唱歌不好', '螞蟻很小'],
        correctIndex: 1,
      ),
    ],
  ),

  // ======== 四年級 上學期 ========
  Lesson(
    id: 'cl-c-4-1-u1',
    subjectId: 'chinese',
    grade: 4,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 1,
    title: '台灣走透透',
    summary: '認識台灣之美',
    content: '台灣雖小，卻擁有高山、平原、海岸、溫泉等豐富地景。\n北部繁華、中部熱情、南部樸實、東部純淨。\n每個地方都有獨特的風土民情。\n\n修辭重點：排比句「北部繁華、中部熱情、南部樸實、東部純淨。」',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「北部繁華、中部熱情、南部樸實、東部純淨」是什麼修辭？',
        options: ['譬喻', '擬人', '排比', '誇飾'],
        correctIndex: 2,
        explanation: '用相同結構並列四個短句，是「排比」。',
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一個不是台灣的地景特色？',
        options: ['高山', '平原', '沙漠', '溫泉'],
        correctIndex: 2,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-4-1-u2',
    subjectId: 'chinese',
    grade: 4,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 2,
    title: '科學家的眼睛',
    summary: '培養觀察力',
    content: '達爾文花了五年環遊世界，仔細觀察不同島嶼上的動物，\n才寫出《物種起源》。\n\n科學家的成就，來自三件事：\n① 好奇心　② 持續觀察　③ 勇於求證',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '達爾文的著作是？',
        options: ['相對論', '物種起源', '本草綱目', '夢的解析'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一項「不是」科學家必備的態度？',
        options: ['好奇心', '持續觀察', '勇於求證', '相信謠言'],
        correctIndex: 3,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-4-1-u3',
    subjectId: 'chinese',
    grade: 4,
    track: CurriculumTrack.core,
    semester: Semester.first,
    unit: 3,
    title: '誠實的價值',
    summary: '品德故事：一諾千金',
    content: '古時候有個人叫季布，答應別人的事一定做到。\n有句話說：「得黃金百斤，不如得季布一諾。」\n意思是：得到一百斤黃金，還不如季布一句承諾值錢。\n\n誠實和守信，比金錢更珍貴。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '「一諾千金」是什麼意思？',
        options: ['答應的話值很多錢', '講話很便宜', '不要說話', '金子很多'],
        correctIndex: 0,
      ),
    ],
  ),

  // ======== 四年級 下學期 ========
  Lesson(
    id: 'cl-c-4-2-u1',
    subjectId: 'chinese',
    grade: 4,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 1,
    title: '環保小尖兵',
    summary: '愛護地球從自己做起',
    content: '地球只有一個，我們要好好愛護它。\n日常生活中可以做：\n• 隨手關燈、關水龍頭\n• 自備購物袋、水壺\n• 垃圾分類、資源回收\n• 節能減碳、多搭大眾運輸\n\n每個小動作，都在為地球減少一分負擔。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '下列哪一項行為「不」環保？',
        options: ['自備水壺', '使用一次性餐具', '搭公車', '關燈'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「節能減碳」的「節」意思是？',
        options: ['節日', '節省', '關節', '季節'],
        correctIndex: 1,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-4-2-u2',
    subjectId: 'chinese',
    grade: 4,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 2,
    title: '世界之旅',
    summary: '認識世界文化',
    content: '巴黎的鐵塔高聳入雲，東京的櫻花嬌豔綻放，\n紐約的高樓比鄰而立，埃及的金字塔神祕古老。\n\n透過閱讀和旅行，我們能開闊視野、尊重不同文化。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '鐵塔位於哪個城市？',
        options: ['東京', '紐約', '巴黎', '開羅'],
        correctIndex: 2,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '金字塔位於哪個國家？',
        options: ['日本', '美國', '法國', '埃及'],
        correctIndex: 3,
      ),
    ],
  ),
  Lesson(
    id: 'cl-c-4-2-u3',
    subjectId: 'chinese',
    grade: 4,
    track: CurriculumTrack.core,
    semester: Semester.second,
    unit: 3,
    title: '母親的手',
    summary: '親情散文',
    content: '媽媽的手，不是細嫩柔軟的手，\n而是一雙粗糙、布滿皺紋的手。\n那雙手為我煮飯、洗衣、縫補衣裳，\n每一條皺紋，都是愛的痕跡。\n\n修辭：運用對比（不是…而是…）突顯主題。',
    questions: [
      Question(
        id: 'q1',
        type: QuestionType.multipleChoice,
        prompt: '作者如何形容母親的手？',
        options: ['又細又嫩', '粗糙布滿皺紋', '又冰又冷', '潔白如雪'],
        correctIndex: 1,
      ),
      Question(
        id: 'q2',
        type: QuestionType.multipleChoice,
        prompt: '「皺紋是愛的痕跡」運用了什麼修辭？',
        options: ['譬喻', '擬人', '排比', '雙關'],
        correctIndex: 0,
      ),
    ],
  ),
];
